- .github/actions/dependencies/action.yml
- .github/actions/llvm-build/action.yml
- .github/workflows/builds.yml
- .github/workflows/lint.yml
- CMakeLists.txt
- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/materialization/JNIImplementationLayer.cpp
- src/jllvm/materialization/LambdaMaterialization.hpp
- src/jllvm/vm/GarbageCollector.cpp
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/JIT.hpp
- tools/main.cpp
This PR adds two simple GitHub Actions Workflows:
* builds.yml: Which verifies that our commits and pull requests properly build and run through tests
* lint.yml: Which lints only changed lines of code in a PR or commit for either linting issues or code style/formatting violations
Part of the complexity is installing all the dependencies. The action.yml in dependencies installs basically all readily available dependencies that we need (Python, cmake, JDK, Compilers, ccache).
The action.yml in llvm-build does a build of the LLVM 16 release branch and caches it (as it otherwise takes roughly 2 hours to build). The advantage of building our own LLVM are that we can use better debugging options such as sanitizers and are not reliant on any kind of repository but the source repository.
While …
> [CI] Add initial CI

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/llvm-miscompile.java
The `noalias` attribute on return types of functions has additional special semantics in LLVM. According to the LangRef, it makes LLVM assume that the pointer returned by the function is unique AND that it comes from the system allocator directly.
The latter has bad consequences in our case however. It makes LLVM assume that stores to the objects memory that are not read are dead and can be removed. This is incorrect in our case however as the GC relies on code setting the class object and attempts reading it. LLVM deleting the store of the class object however leads to it remaining null, and the GC crashing when trying to parse the heap during garbage collection.
This PR fixes that issue by removing the inaccurate `noalias` attribute and replacing it with the `allockind` attribute …
> [llvm] Fix crash due to a wrong function attribute on our allocation function

- src/jllvm/main/Main.cpp
- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/materialization/JNIImplementationLayer.cpp
- tests/Execution/jni-primitives.java
- tests/Execution/less-than-int-args.java
Since Javas operand stack essentially always uses at least `int`, we have to truncate these before making a call to a function taking `byte`, `short` or any other integer type less than `int`.
> [codegen] Fix calls to functions taking integer arguments smaller than `int`

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/less-than-int-fields.java
Since Javas operand stack operates on at least 32 bit integers we have to make sure to properly truncate or sign extend any values with a bitwidth less than that.
> [codegen] Fix reads and writes to fields with types smaller than `int`

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/idiv.java
This PR includes support for creating appropriate LLVM instructions on processing the idiv JVM instruction. Furthermore, the processing of the iadd instruction is modified s.t. LHS and RHS match the order defined by the JVM specification. 
Fixes https://github.com/JLLVM/JLLVM/issues/31
> [instruction] Add support for idiv instruction

- src/jllvm/main/Main.cpp
- src/jllvm/vm/StackMapRegistrationPlugin.cpp
- tests/Execution/object-array-ops.java
The current JITLink plugin that extracts the stackmap out of object files still had hardcoded section names for just Linux, but not macOS. This caused the garbage collector to collect objects that were still referenced by local variables causing nasty bugs.
Additionally, libunwind seems to not be capable of writing to caller saved regsiters within a stackframe (at least it seemingly does not apply the changes). We therefore disable this optimization on macOS for the moment, and let it spill the code instead.
Attached test was originally meant to be a simple regression test for array operations, turned out to also hit the GC issue on macOS.
> [GC] fix stackmap interaction on macOS

- src/jllvm/object/ClassLoader.cpp
- src/jllvm/object/ClassLoader.hpp
- src/jllvm/vm/VirtualMachine.cpp
- tests/Execution/circular-class-loader.java
The class loader currently incorrectly immediately initializes class objects as they are loaded. This is problematic however in cases such as two static initializers having circular dependencies on each other. This would previously crash due to loading a class object twice and creating linker errors.
This PR fixes that by following the spec more closely: https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-5.html#jvms-5.5
We first create the class object, mark it as uninitialized (or prepared as the spec calls it), then initialize super classes and interfaces. If these do any lookups or similar for the currently-under- initialization class object they will then succeed without issues.
I have added a test demonstrating the behaviour. It uses circular references between static fields …
> [classloader] Implement circular initialization of classes

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/object/ClassObject.cpp
- src/jllvm/object/ClassObject.hpp
- tests/Execution/superclass-fields.java
The current implementation only ever considered fields in the immediate class, but not any of its super classes. Implementing this was trivial by just traversing the superclasses right afterwards, bottom up. Since Java only allows single inheritance there is no complicated traversal algorithm.
> [codegen] Implement field lookup into super classes

- .clang-tidy
- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/control-flow-path-dependent-operand-stack.java
This PR creates a new operand stack that also considers the control flow. This is done by getting and setting the top of stack according to basic blocks.
fixes https://github.com/JLLVM/JLLVM/issues/23
> [codegen] Implement control flow path dependent operand stack

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/ireturn.java
This PR includes support for creating appropriate LLVM instructions on processing the ireturn JVM instruction. 
fixes https://github.com/JLLVM/JLLVM/issues/39
> [instruction] Add support for ireturn instruction

- .github/workflows/lint.yml
Recent updates to the `jammy-updates` repository seem to now provide clang 15. 
This has had the negative side effect of seemingly breaking our lint builder since it was now in conflict with the LLVM APT repository with which packages provide which files.
Fix this by just using the ubuntu packages from now on. This has the nice side effect of them being more granular and a lot faster to install
> [CI] Switch clang-tidy and clang-format installations to Ubuntu repositories

- src/jllvm/class/Descriptors.hpp
- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/materialization/ByteCodeCompileUtils.cpp
- src/jllvm/materialization/JNIImplementationLayer.cpp
- src/jllvm/object/ClassLoader.cpp
- tests/Execution/integer-casts.java
- tests/Execution/less-than-int-fields.java
The original code incorrectly assumed that `char` was a signed type. The JVM spec specifies it as (the only!) unsigned type however, so doing a signed extension leads to correct and unexpected results in various places.
This PR fixes this issue in various places by checking the descriptor whether the integer type is signed or unsigned and using proper instructions accordingly.
Fixes https://github.com/JLLVM/JLLVM/issues/44
> [codegen] use `zext` instead of `sext` when working with `char`

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/iand-ior-ineg-ixor.java
This PR includes support for creating appropriate LLVM instructions on processing the iand, ior, ineg and ixor JVM instructions.
fixes https://github.com/JLLVM/JLLVM/issues/47
> [instruction] Implement iand, ior, ineg and ixor instructions

- src/jllvm/main/Main.cpp
- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/materialization/JNIImplementationLayer.cpp
- src/jllvm/materialization/JNIImplementationLayer.hpp
- src/jllvm/materialization/LambdaMaterialization.hpp
- src/jllvm/object/Object.hpp
- src/jllvm/vm/CMakeLists.txt
- src/jllvm/vm/JIT.hpp
- src/jllvm/vm/JNIImplementation.cpp
- src/jllvm/vm/NativeImplementation.cpp
- src/jllvm/vm/NativeImplementation.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
- tests/Execution/ObjectHashCode.java
The high level API builds on top of the JNI interface, simply doing casts to go from the JVM agnostic to classes specific to our JVM implementation. The API essentially works by creating 'Model' classes in C++ which should mirror the class from Java. 
Within the 'Model' class, one defines (possibly static) methods with the exact same name and signatures (translated to C++ types) as are used in Java. One then only has to list the name of the Java class and the list of methods implemented in static members of the model class and register in a 'VirtualMachine' instance.
As a simple demonstration of how to use the API, a model class for Javas 'Object' was implemented with an implementation of `hashCode`. It lazily computes a unique id for a Java object and then stores it within the object …
> [vm] Add a high level API to easily implement 'native' methods of Java in C++

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/int-shifts.java
This PR includes support for creating appropriate LLVM instructions on processing the ishl, ishr and iushr JVM instructions.
fixes https://github.com/JLLVM/JLLVM/issues/51
> [instruction] Implement int shifting instructions

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/object/ClassObject.cpp
- src/jllvm/object/ClassObject.hpp
- src/jllvm/object/Object.cpp
- src/jllvm/object/Object.hpp
- src/jllvm/vm/JIT.cpp
- tests/Execution/instanceof.java
This is a rather simple implementation of the op specified here https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-6.html#jvms-6.5.instanceof.
I opted to implement it in C++ instead of LLVM IR because a lot of the supporting infrastructure already existed for things like iterating over all interfaces etc.
Fixes https://github.com/JLLVM/JLLVM/issues/55
Depends on https://github.com/JLLVM/JLLVM/pull/56 within the tests
> [instruction] Implement `instanceof`

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/object/ClassLoader.cpp
- src/jllvm/object/ClassObject.cpp
- src/jllvm/object/ClassObject.hpp
- src/jllvm/vm/VirtualMachine.cpp
The codebase has a lot of loops traversing through the superclasses of a class object. By adding this iterator and the convenient `getSuperClasses` method we can use very nice ranged `for` loops and the various algorithms in C++s `<algorithm>` header (and similar functions in LLVM).
> [object][NFC] Add convenient iterator over superclasses

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
Update codegen for `new` to load from `fieldAreaPtr`  instead of `classObject` as mentioned in #61.
> [fix] Fix wrong assignment in codegen for new

- src/jllvm/main/Main.cpp
- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/jni-primitives.java
This PR includes support for creating appropriate LLVM instructions on processing the `fconst` JVM instructions.
TODO:
* Change the native jni-methods do print floats correctly. Currently not implemented because `llvm::raw_ostream` does not work  `std ` stream manipulators and the default formatting in always in scientific notation.
> [instruction] Add support for `fconst` instructions (#4)

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/fload-fstore.java
- tests/Execution/jni-primitives.java
This PR includes support for creating appropriate LLVM instructions on processing the `fload` and `fstore` JVM instructions.
> [instruction] Add support for `fload` and `fstore` instructions (#4)

- src/jllvm/main/Main.cpp
- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/support/Bytes.hpp
- tests/Execution/fload-fstore.java
This PR includes support for creating appropriate LLVM instructions for the `lcd` instruction for constant floats of the JVM.
It also fixes a bug, where consume constructed the required type with the given bytes instead of creating it.
Additionally it adds correct formatting for floating point types to `trivialPrintFunction`.
> [instruction] Add support for `lcd` instruction for constant floats (#7) 

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/vm/StringInterner.cpp
- tests/Execution/integer-comparisons.java
- tests/Execution/string-literals.java
This PR includes support for creating appropriate LLVM instructions on processing the `if_acmpeq` and `if_acmpeq`  JVM instructions.
It also fixes a bug, where `buffer` in `createString` could reference arrays which could later be dealocated resulting in invalid data being inserted into `createString`. (rust would have caught this)
> [instruction] Add support for `if_acmp` instructions (#63)

- CMakeLists.txt
See "Build JLLVM" step in https://github.com/JLLVM/JLLVM/actions/runs/5025014536/jobs/9011439566 
The linker is currently emitting a huge amount of warnings due to differing symbol visibility. The simple reason is that LLVMs cmake files build using `-fvisibility-inlines-hidden` but we don't. This just replicates LLVMs logic for when to use the flag to avoid warnings (https://github.com/llvm/llvm-project/blob/c9e3840c832d4c3fbbf57f0a8c90ae3d80af8913/llvm/cmake/modules/HandleLLVMOptions.cmake#L368).
> [cmake] fix warnings on macOS about weak symbol visibility

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/vm/JIT.cpp
- tests/Execution/fadd.java
- tests/Execution/fdiv.java
- tests/Execution/fmul.java
- tests/Execution/fneg.java
- tests/Execution/frem.java
- tests/Execution/fsub.java
This PR includes support for creating appropriate LLVM instructions on processing the `fadd`, `fdiv`, `fmul`, `fneg`, `frem` and `fsub` JVM instructions.
> [instruction] Add support for float arithmetic instructions (#4)

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/object/ClassLoader.cpp
- src/jllvm/object/ClassLoader.hpp
- src/jllvm/object/ClassObject.cpp
- src/jllvm/object/ClassObject.hpp
- src/jllvm/object/Object.hpp
- src/jllvm/vm/NativeImplementation.cpp
- src/jllvm/vm/NativeImplementation.hpp
- src/jllvm/vm/VirtualMachine.cpp
- tests/Execution/class-object-as-java-object.java
`Class` is Java's most fundamental mechanism for reflection and very important to its execution model. We additionally utilize it as RTTI object and owner of V and ITables. These have so far been in an internal format however which was incompatible with the `Class` shipped with OpenJDK.
This patch fixes that by making it a proper java object and synchronizing its field layout with OpenJDK. The largest complexity in the patch is actually a change to the class loader. Since `Class` is also its own class object, a special "bootstrap load sequence" has to be done in the class loader on startup. Some of the fields from OpenJDK are likely to require special initialization by the VM that is currently not yet done and left as future exercise once required.
Additionally, because testing would be …
> [object][instruction] Make `ClassObject` a proper Java object

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/faload-fastore.java
This PR includes support for creating appropriate LLVM instructions on processing the `faload` and `fastore` JVM instructions.
TODOs:
* Implement throwing `NullPointerException` if arrayref is null
* Implement throwing  `ArrayIndexOutOfBoundsException` if index is not within the bounds
> [instruction] Add support for float array instructions (#4)

- src/jllvm/class/ByteCodeIterator.cpp
- src/jllvm/class/ByteCodeIterator.hpp
- src/jllvm/class/CMakeLists.txt
- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/control-flow-false-positive.java
This is achieved by creating a new byte code iterator abstraction which centralizes our logic for iterating over JVM bytecode, allowing reuse of the logic both when creating the basic blocks and generating LLVM IR.
Previously the basic block creation would interpret everything that looks like a branch instruction as a branch instruction. This would create incorrect basic blocks with no terminators which would make the verifier in LLVM fail as well as some optimization passes.
The implementation was intentionally kept very simple and a large focus was made on having to modify as little code as possible, keeping the code for all instructions implemented so far identical. One could definitely build a nicer abstraction with sum types that already contain parsed data for the instruction but …
> [codegen] fix false positives when creating basic blocks

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/float-casts.java
This PR includes support for creating appropriate LLVM instructions on processing the `f2d`, `f2i`  and `f2l` JVM instructions.
> [instruction] Add support for float cast instructions

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/ireturn.java
When returning integers in functions returning `i16` or smaller we have to truncate the `i32` first to not create an invalid LLVM IR module that does not verify due to `ret` type mismatches. Additionally, booleans have to be treated specially, as the spec states that converting to a boolean return type has to be done via a bitmask with 1.
> [instruction][fix] Implement `ireturn` for functions returning smaller integer types

- src/jllvm/vm/VirtualMachine.cpp
- tests/Execution/abstract-class-interface.java
An abstract class can declare a method of a super interface and "overwrite" it, which would lead to the method not being found by the JIT. This is fine since any subclasses of the abstract class will override the method. Nevertheless, simply ignore errors during lookup in the JIT instead of crashing
> [fix] gracefully handle abstract class method declaration of interface class

- src/jllvm/object/ClassLoader.cpp
- src/jllvm/object/ClassObject.cpp
- src/jllvm/object/ClassObject.hpp
- tests/Execution/super-class-super-interface.java
The iterators used to enumerate all interfaces (either in any order or topological) previously only took into account direct superinterfaces and their transitive superinterfaces but not the (direct and indirect) superinterfaces of superclasses. This would lead to failures to allocate and populate ITables for specific classes followed by runtime crashes when `invokeinterface` did not find an ITable entry.
This patch fixes that by changing the GraphTraits to create a whole classgraph out of all class objects and simply use a filter to only output interfaces. This makes the superinterfaces of superclasses reachable as well.
The implementation of ClassObject was also adjusted to ease the implementation.
> [fix] properly take superinterfaces of superclasses into account as well

- .clang-tidy
This PR deals with the issue of the `lint-run` action being really slow by removing the `clang-static-analyzer` checks, which are more burdensome than helpful.
> [CI] Remove unnecessary checks from `.clang-tidy`

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/monitor-enter-exit.java
- tests/Execution/try-catch.java
Multi threading is currently a non-goal for us, therefore this PR currently implements them as doing nothing but the require operand stack manipulation.
We might still be executing and compiling `synchronized` blocks however, hence their implementations are required.
A `athrow` stub is required due to `synchronized` catching any exception and then rethrowing it. This can currently never be executed, so the stub that does the right stack manipulation should suffice for now
Depends on https://github.com/JLLVM/JLLVM/pull/96
> [instruction] add the most basic implementation of `monitorenter`, `monitorexit` and `athrow`

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/vm/NativeImplementation.hpp
- tests/Execution/assert.java
- tests/Execution/monitor-enter-exit.java
- tests/Execution/try-catch.java
Any uses of `assert` within a class leads to the creation of a class initializer which queries the assertion status from the class loader and VM: https://godbolt.org/z/9a6q675bx
This PR implements the 'native' method called from `Class.desiredAssertionStatus` to allow our VM to load class files that contain `assert` (even if they're never executed). `assert`s themselves do not yet work (nor can be compiled) since it contains `athrow` of `AssertionError`.
I currently made it simply match whether the VM is compiled in debug or release but this isn't really proper. Rather, a command line option should be added in the future to make this user configurable, but this is beyond the scope of this PR
Depends on https://github.com/JLLVM/JLLVM/pull/95
> [vm] implement basic implementation for 'assert' class initializers

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/integer-casts.java
This PR fixes the bug, where the argument to `CreateSExt` or `CreateZExt` in `codeGenBody` was the original integer value not the truncated one. 
Fixes #90
> [fix] Fix wrong assignment in codegen for narrowing integer casts

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/ldc2_w.java
This PR includes support for creating appropriate LLVM instructions on processing the `ldc_w` and `ldc2_w` JVM instructions.
Fixes: #17
> [instruction] Add support for `ldc_w` and `ldc2_w` instructions

- src/jllvm/class/ClassFile.hpp
- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/object/ClassLoader.cpp
- src/jllvm/object/ClassObject.hpp
- src/jllvm/vm/VirtualMachine.cpp
- tests/Execution/invoke-virtual-interface-method.java
- tests/Execution/private-invoke-virtual.java
- tests/Execution/simple-package-private-override.java
The current vtable slot assignment was prematurely optimized to the point of being incorrect. In particular, calling private methods was not possible as they have been filtered out. In the future, if we were to fully implement the complicated package private overriding scenario described here https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-5.html#jvms-5.4.5 it'd likely stand in our way too.
For now, just simplify the implementation and give a vtable slot to every non-static method. Then properly assign method according to the method selection described in 5.4.6 (this is the same procedure as for interface methods). Additionally, package private calls from the same "package" was implemented (this is required to load `Class`) and tests annotated XFAIL with todos for the future were …
> [object] make vtable slot assignment correct first, optimized later

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/object/Object.hpp
- src/jllvm/vm/GarbageCollector.cpp
- src/jllvm/vm/GarbageCollector.hpp
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/JIT.hpp
- src/jllvm/vm/NativeImplementation.cpp
- src/jllvm/vm/NativeImplementation.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
- tests/Execution/athrow.java
This if the first step for exception handling in our JVM. As described in https://github.com/JLLVM/JLLVM/issues/6, due to shortcomings in LLVMs builtin exception handling when using a relocating GC, we are opting to build the mechanism ourselves. This is achieved by manually generating code to check if and exception was thrown and do appropriate dispatch.
This patch is the first patch in this series which implements `athrow` and the unwinding mechanism. Throwing essentially sets a global called `activeException` to the now active exception. Unwinding is done by checking whether this global is set and returning from the function if true. This requires generating code after every instruction might cause unwinding.
Next patches will create code for dispatching into catch handlers.
Fixes …
> [instruction] Implement `athrow` and unwinding mechanism

- src/jllvm/class/ClassFile.hpp
- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/vm/JIT.cpp
- tests/Execution/try-catch.java
Catching exceptions works by having a range of bytecode offsets "under protection" of a handler. Each handler has an associated handler program counter and a catch type.
This PR generates appropriate code using the handlers to perform dynamic instance of checks on the exception object and then jump to the corresponding handler.
Special care had to be taken in the order of handlers since it determines which handler is checked first.
Depends on https://github.com/JLLVM/JLLVM/pull/103
Fixes https://github.com/JLLVM/JLLVM/issues/6
> [codegen] implement dispatch chains to catch handlers

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
If our helper class managed to optimize class loading by computing constants from already loaded class objects it is redundant to then generate dispatch code for EH. This especially hurts because LLVM has a very hard time optimizing these out since as far as it knows, its just a global variable that has nothing to do with "exception handling" semantics.
Simply detect if constants had been returned from class loading operations and avoid generating the EH dispatch code.
> [codegen] reduce amount of EH dispatch code with optimized class object loading

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/vm/CMakeLists.txt
- src/jllvm/vm/GarbageCollector.cpp
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/MarkSanitizersGCLeafs.cpp
- src/jllvm/vm/MarkSanitizersGCLeafs.hpp
One of the hardest to debug errors once they occur are errors related to GC. Most of these are usually a relocation not being updated or maybe the GC collecting an object to early.
Either way, the earlier and faster we can detect these errors the better. This patch adds support for using ASAN to instrument the `toSpace` aka the not actively in use heap area by poisoning it to make any reads and writes instrumented with ASAN fail with a backtrace and error message. To make this more even more effective, passes from LLVM are added to our JIT to also instrument our produced Java code.
This makes it possible to also detect any incorrect memory operations in Java due to codegen errors and similar.
Demonstration code:
```cpp
auto* savePtr = m_activeException.get();
// causes relocation of …
```
> [GC][codegen] add extra GC error detection using ASAN

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/jni-primitives.java
This PR includes support for creating appropriate LLVM instructions on
processing the `dconst0`, `dconst1`, `lconst0` and `lconst1` JVM instructions.
> [instruction] Add support for all `const` instructions

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/dadd.java
- tests/Execution/ddiv.java
- tests/Execution/dmul.java
- tests/Execution/dneg.java
- tests/Execution/drem.java
- tests/Execution/dsub.java
- tests/Execution/ladd.java
- tests/Execution/ldiv.java
- tests/Execution/lmul.java
- tests/Execution/lrem.java
- tests/Execution/lsub.java
This PR includes support for creating appropriate LLVM instructions on processing the `dadd`, `ddiv`, `dmul`, `dneg`, `drem` , `dsub`, `ladd`, `ldiv`, `lmul`, `lneg`, `lrem`  and `lsub` JVM instructions.
> [instruction] Add support for all arithmetic instructions

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/double-comparisons.java
This PR includes support for creating appropriate LLVM instructions on processing the `dcmpq` and `dcmpl` JVM instructions.
> [instruction] Add support for double comparisons

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/double-casts.java
This PR includes support for creating appropriate LLVM instructions on processing the `d2f`, `d2i` and `d2l` JVM instructions.
> [instruction] Add support for double cast instructions

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
I think we can all agree that `codeGenBody` has gotten a bit large. The `match` statement itself isn't that horrible IMO but rather a lot of the state and variables floating around which has lead to the creation of lambdas and inline code which should have really been functions but weren't out of laziness of not wanting to pass dozens of parameters around.
This patch therefore focus on fixing that part of the equation by encapsulating all things related to codegen within a class, making it possible to access all state relevant for the generation of code from within any methods of that struct. This most importantly makes it easier to extract code from e.g. `match` statements to allow code reuse.
Some functions, like the calculation of basic blocks, or the lambdas for EH generation have …
> [refactor][NFC] Consolidate state from `codeGenBody` into struct

- CMakeLists.txt
- cmake/CPM.cmake
- unittests/CMakeLists.txt
- unittests/HelloWorldTest.cpp
We are currently only relying on integration tests for our test suite which nicely ensures that all components are working but has the issue of not really properly allowing to test small details/aspects within our components.
I'd therefore like to add Catch2 as a unit testing library. My concrete use case is that I want to test various allocation patterns in the GC for correctness in an upcoming revision.
To conveniently add the library everywhere without having to vendor it, CPM was used which automatically downloads the library, includes it in cmake and makes it available. Additionally, Catch2 has great integration with test discovery with `ctest` (the testing driver we use), making it run all `TEST_CASE`s in a single process in parallel
A `HelloWorldTest` was added as …
> [test] add Catch2 as unit testing library

- src/jllvm/materialization/JNIImplementationLayer.hpp
- src/jllvm/materialization/LambdaMaterialization.hpp
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/JIT.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
These have so far been directly implemented in the main Dylib. Implementing them in a separate dylib allows reuse of that dylib in the link order of other dylibs. Specifically, I'd like to reuse the implementation of these internal symbols in the JNI bridge dylib as well.
Additionally, a nice API was added to add these methods and the implementations were moved to the VirtualMachine. The reason for the latter is that the implementations of these functions should have more access to all the required state (including active exception, class loader, etc) available from the Virtual machine without having to needlessly pass them into the JIT instance.
> [refactor][NFC] Move implementations of internal functions into its own Dylib

- src/jllvm/gc/GarbageCollector.hpp
- src/jllvm/gc/RootFreeList.hpp
- src/jllvm/main/Main.cpp
- src/jllvm/materialization/JNIImplementationLayer.cpp
- src/jllvm/vm/NativeImplementation.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
The JNI spec requires `jobject` (which in our implementation will be an alias to `GCRootRef`) to be rooted. This PR therefore adjusts the bridge code generation to automatically create and delete these roots. Since our higher level interface in NativeImplementation.hpp builds on top of the JNI, it had to also be adjusted to now work on GCRootRef instead of raw pointers.
Documentation and implementations were therefore adjusted accordingly.
Depends on https://github.com/JLLVM/JLLVM/pull/116
> [JNI][NFC] Exclusively use GC roots in the JNI interface

- src/jllvm/vm/StringInterner.cpp
- src/jllvm/vm/StringInterner.hpp
- src/jllvm/vm/VirtualMachine.cpp
- tests/Execution/string-interner-gc.java
We cannot load the string class object lazily due to it occurring during bytecode compilation. Bytecode compilation, due to being lazy/on-demand is implemented using trampolines in the JIT which do a kind of "context-switch", making the Java stack unreachable for the unwinder and causing the GC to think all objects so far are unreachable. This would cause all of them to be deleted causing massive issues.
This patch fixes that by simply eagerly loading the string object for the string interner.
> [vm] eagerly load string class object for string interner

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/object/ClassLoader.cpp
- src/jllvm/object/ClassLoader.hpp
- src/jllvm/object/ClassObject.cpp
- src/jllvm/object/ClassObject.hpp
- src/jllvm/vm/StringInterner.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
- tests/Execution/static-class-loader-gc.java
As we recently discovered, due to the context switching of the JITs trampoline, the Java stack becomes unreachable to the GC while we are compiling bytecode. If a GC then occurs due to running Java code, the GC deletes essentially all objects on the Heap.
It is therefore required that Java code is NOT executed during compilation. Prior to this PR, the class loader would initialize class objects during compilation of stubs (whose whole responsibility was the loading of classes) which would then execute Java code if the class had a class initializer.
This PR fixes that by reworking how classes are initialized. First, the responsibility is taken away from the class loader as this was simply the incorrect place to do so. According to the spec, classes are only initialized by specific …
> [vm] stop running class initializers during bytecode compilation

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/materialization/LambdaMaterialization.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
- tests/Execution/checkcast.java
- tests/Execution/class-cast-exception-error.java
This instruction is very similar to `instanceof` except it throws a class cast exception instead of returning false. Its behaviour also differs in the case of null, counting it as a success rather than failure.
Patch also includes minor refactorings I felt were necessary while I was implementing it.
Fixes https://github.com/JLLVM/JLLVM/issues/102
> [instruction] Implement `checkcast` instruction

- src/jllvm/class/ByteCodeIterator.hpp
- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/blocks-with-different-types-on-stack.j
- tests/Execution/handler-stack-pointer.j
This PR adds type information the the `OperandStack`, thereby enabling popping without having to specify the type.
It also allows for checking the type of the popped value in order to implement operations with multiple forms depending on the type.
> [codegen] Add type information to `OperandStack`

- src/jllvm/main/Main.cpp
- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/dadd.java
- tests/Execution/ddiv.java
- tests/Execution/dmul.java
- tests/Execution/dneg.java
- tests/Execution/drem.java
- tests/Execution/dsub.java
- tests/Execution/float-casts.java
- tests/Execution/ldc2_w.java
- tests/Execution/long-casts.java
This PR includes support for creating appropriate LLVM instructions on processing the l2d, l2f and l2i JVM instructions. Additionally, this PR improves precision for double prints. Thus, double values now have higher precision than float values.
fixes https://github.com/JLLVM/JLLVM/issues/133
> [instruction] Implement l2d, l2f and l2i instructions and change precision for double prints

- src/jllvm/class/ByteCode.def
- src/jllvm/class/ByteCodeIterator.cpp
- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- tests/Execution/wide.j
This PR includes support for creating appropriate LLVM instructions on processing the `wide` JVM instruction.
Implementing `wide` in conjunction with `ret` is left as a TODO, since  `ret` is yet to be implemented.
> [instruction] Add support for `wide` instruction

- src/jllvm/class/ClassFile.hpp
- src/jllvm/materialization/CodeGeneratorUtils.cpp
- src/jllvm/object/ClassLoader.cpp
- tests/Execution/final-method-call.java
Since our new `invokevirtual` implementation it is now perfectly possible to create direct calls to methods if after resolution we know they can't be overwritten. This is the case for any private or final instance methods for example.
This PR uses that capability to reduce the amount of V-Table slots we create for class objects.
> [object][NFC] reduce number of VTable slots

- src/jllvm/materialization/CodeGeneratorUtils.cpp
- src/jllvm/object/ClassLoader.cpp
- src/jllvm/object/ClassObject.cpp
- src/jllvm/object/ClassObject.hpp
- src/jllvm/vm/VirtualMachine.cpp
The refactoring opportunity mostly comes from adding an additional `m_tableSize` field to class object, removing previously repeatedly redundant work done calculating what was essentially the table size of classes or interfaces. Other code was additionally simplified and renamed to more consistent terminology.
> [object][NFC] Refactor assignment of V-Table and I-Table slots a bit

- src/jllvm/materialization/CodeGeneratorUtils.cpp
- src/jllvm/materialization/CodeGeneratorUtils.hpp
- src/jllvm/object/ClassLoader.cpp
- tests/Execution/private-invoke-interface.java
Similar to https://github.com/JLLVM/JLLVM/pull/142, this reduces the amount of slots allocated in an I-Table for an interface. Interface methods can't actually be final, hence no test was added for that case here. Private interface methods can't be overwritten (same logic as for normal class methods) hence there is no need to create slots for them.
Depends on https://github.com/JLLVM/JLLVM/pull/145
> [object][NFC] reduce number of Itable slots

- src/jllvm/materialization/CodeGenerator.cpp
- src/jllvm/materialization/CodeGenerator.hpp
- src/jllvm/materialization/CodeGeneratorUtils.cpp
- src/jllvm/materialization/JNIImplementationLayer.cpp
This adds nothing but the name of the function, currently still in the mangled form, as debug info in the produced LLVM. This is luckily enough to have the debugger display the name of the function in the callstack.
Example of callstack in GDB:
> [codegen] Add most basic debug info to Java functions

- src/jllvm/gc/GarbageCollector.cpp
- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/materialization/CodeGeneratorUtils.cpp
- src/jllvm/materialization/JNIImplementationLayer.cpp
- src/jllvm/materialization/LambdaMaterialization.hpp
- tests/Execution/dynamic-stack-usage-gc.java
Unwinding the stack is a very complicated topic and it turns out DWARF CFI is very complicated. When working with deeper call-stacks I have discovered multiple occurrences of the unwinder being unable to retrieve the stack pointer and crashing instead.
I have tried multiple combinations of: using libunwind instead of libgcc, all kinds of compiler flags, both in our JIT and C++ compiler, testing with GCC, using the level 1 libunwind API and so on and on, but would usually end up just having crashes elsewhere.
The version that basically worked perfectly for everything I've tested was fetching the Canonical Frame Address (CFA) ~~which as far as I can tell is equal to the stack pointer but always available~~ is equal to the stack pointer at the beginning of the function, which seemingly works …
> [codegen][gc] reliably retrieve RSP during unwinding

- .github/workflows/builds.yml
- .github/workflows/lint.yml
See https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/ for details.
I'd like to enable the merge queues beta to make sure that any pull request we are merging into `main` is actually tested with up-to-date `main`. This should make it impossible for `main` to ever be red since PRs are scheduled with the current HEAD and only merged after CI has successfully completed.
This PR adds `merge_group` as trigger to all our required CIs as is required for the feature to work (https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions)
> [CI] Enable GitHub Actions merge queue

- src/jllvm/vm/NativeImplementation.cpp
- src/jllvm/vm/NativeImplementation.hpp
- src/jllvm/vm/VirtualMachine.hpp
- tests/Execution/double-float-bits.java
These are simple native methods to convert between integer reinterpretations and the actual floating point number.
> [native] implement `Double` and `Float` bit conversions

- src/jllvm/vm/NativeImplementation.cpp
- src/jllvm/vm/NativeImplementation.hpp
- tests/Execution/system-nanoTime.java
This a very simple method useful for measuring time and even used in a few places in JVM startup. Testing it is kind of hard since it is non-deterministic. The only real properties to test is therefore that it is positive and monotonic
> [native] implement `System.nanoTime`

- src/jllvm/gc/GarbageCollector.cpp
- tests/Execution/super-class-fields-gc.java
This is a very embarrassing oversight :) So far we've only been traversing into the direct fields of a class but forgot to traverse into the indirect fields of a class that it gained through inheritance.
This PR does a simple correct implementation for now to unblock work with a TODO how to properly optimize this in the future.
> [gc] introspect into superclass fields as well

- src/jllvm/materialization/CodeGenerator.cpp
- tests/Execution/recursive-function-debug-info-crash.java
LLVM requires any call to an inlineable function with debug info to have debug line location, otherwise it'd throw a verifier error. Even tho we are a per-method JIT, this can still occur in self-recursive functions as LLVM could inline the function into itself. This PR just adds some dummy debug line location for the time being.
> [codegen] use dummy debug location to avoid LLVM verifier error

- src/jllvm/materialization/CodeGeneratorUtils.cpp
- tests/Execution/relocation-in-stub.java
The stubs might do garbage collection as part of executing a class initializer. Any arguments passed into the stub, that are then passed to the actual callee, have to both be 1) found by the GC and 2) relocated by the GC. 1) worked perfectly previously as the caller of the stub registers all arguments in the stackmap bug 2) did not. 
This would cause a relocated object to not be updated in the stack frame of the stub and a dangling pointer being passed to the actual callee.
> [codegen] also enable GC in generated stubs

- src/jllvm/gc/RootFreeList.hpp
- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/materialization/ByteCodeCompileLayer.hpp
- src/jllvm/materialization/ByteCodeCompileUtils.cpp
- src/jllvm/materialization/ByteCodeCompileUtils.hpp
- src/jllvm/materialization/ByteCodeLayer.cpp
- src/jllvm/materialization/ByteCodeLayer.hpp
- src/jllvm/materialization/ByteCodeMaterializationUnit.cpp
- src/jllvm/materialization/ByteCodeMaterializationUnit.hpp
- src/jllvm/materialization/ByteCodeOnDemandLayer.cpp
- src/jllvm/materialization/ByteCodeOnDemandLayer.hpp
- src/jllvm/materialization/CodeGeneratorUtils.cpp
- src/jllvm/materialization/CodeGeneratorUtils.hpp
- src/jllvm/materialization/JNIImplementationLayer.cpp
- src/jllvm/materialization/JNIImplementationLayer.hpp
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/JIT.hpp
- src/jllvm/vm/NativeImplementation.cpp
- src/jllvm/vm/NativeImplementation.hpp
- src/jllvm/vm/VirtualMachine.cpp
- tests/Execution/reflection-get-caller-class.java
This method is used relatively extensively within the OpenJDK, mostly to provide reflection capabilities. This includes at VM startup. The method also served as a good motivation to implement adding metadata to compiled Java methods that can be fetched during unwinding. This mechanism allows getting reflective information about any Java method from stacktraces. This mechanism can later also be used to implement symbolized stacktraces of exceptions.
The basic mechanism used to implement all of this is 1) adding the metadata into the `prefix` attribute of LLVM functions. These are placed immediately before the function in the resulting assembly. 2) Marking Java functions as originating from Java. This is achieved by putting them into "java" sections. This is required for 3) maintaining a …
> [native] implement `Reflection.getCallerClass` and callstack metadata

- src/jllvm/materialization/CodeGenerator.cpp
- src/jllvm/materialization/CodeGenerator.hpp
- src/jllvm/materialization/CodeGeneratorUtils.cpp
- src/jllvm/materialization/CodeGeneratorUtils.hpp
- src/jllvm/unwind/Unwinder.cpp
- tests/Execution/dead-code.j
This PR fixes the issue of the type-checking pass not generating any stack information for dead code block, causing the compilation to fail. Now only reachable code will be compiled.
> [codegen] Remove compilation of dead code

- src/jllvm/support/Encoding.cpp
- tests/Execution/compact-string-to-utf8.java
The compact encoding used in Java is not UTF-8 put Latin1 which are sadly not identical. Latin1 is essentially a truncated version of UTF-32, only supporting the first 256 codepoints. UTF-8 is only identical in the first 128 codepoints. All after have be encoded in a multi-byte scheme.
> [support] fix java compact encoding to UTF-8 conversion

- src/jllvm/gc/RootFreeList.hpp
- src/jllvm/vm/NativeImplementation.cpp
- src/jllvm/vm/NativeImplementation.hpp
- tests/Execution/unsafe-array-base-and-index.java
- tests/Execution/unsafe-compare-and-set.java
- tests/Execution/unsafe-fences.java
- tests/Execution/unsafe-get-put-volatile.java
The operations implemented here are as far as I could tell the most common uses of `Unsafe` and the ones required for both `System.initPhase1` and `StringBuilder` e.g.
In short, `Unsafe` offers operations to get the byte offset of fields within objects followed by operations that operate on byteoffsets into the these objects. The accessors implemented here and most often used are atomic ones, allowing atomic accesses to fields of a Java objects.
Atomic load, store and xchg are currently implemented with Compiler builtins as C's `_Atomic` and C++s `std::atomic` do not support operating on arbitrary pointers, while these builtins do. C++20 has `std::atomic_ref` that has these capabilities but these are not yet supported in libc++.
In the future all these implementations should actually be …
> [native] initial implementation of `Unsafe`

- src/jllvm/vm/NativeImplementation.hpp
There is really no need to require the user to call `addMember` for us. Since it is a `constexpr` tuple we can do so ourselves from the implementation in `addModel`.
> [native][refactor][NFC] get rid of `addMember`

- src/jllvm/gc/GarbageCollector.cpp
- src/jllvm/gc/GarbageCollector.hpp
- src/jllvm/materialization/JNIImplementationLayer.cpp
- src/jllvm/vm/VirtualMachine.cpp
We currently had issues avoiding double frees of roots when creating roots during JNI calls. The reason is that it is cumbersome to determine whether a root returned by a native function happens to be a root passed into the function or whether it is a global root and whatnot.
Instead, adopt a strategy that is actually mandated by the JNI spec: Create new "local root frames" in which all local roots during a JNI call are allocated that are then automatically freed on return. These also correspond to the `PushLocalFrame` and `PopLocalFrame` functions defined here https://docs.oracle.com/en/java/javase/17/docs/specs/jni/functions.html#pushlocalframe
With these, we can simply pop the frame at the end of a JNI call to free all local roots.
> [JNI] add concept of `local` frames to manage roots during JNI calls

- src/jllvm/vm/CMakeLists.txt
- src/jllvm/vm/JNIImplementation.cpp
- src/jllvm/vm/JNIImplementation.hpp
- src/jllvm/vm/NativeImplementation.cpp
- src/jllvm/vm/NativeImplementation.hpp
- src/jllvm/vm/native/JDK.cpp
- src/jllvm/vm/native/JDK.hpp
- src/jllvm/vm/native/Lang.cpp
- src/jllvm/vm/native/Lang.hpp
For now just group them by their package. Models so far have been in 'java/lang' and 'jdk/internals' and have therefore been split into these two groups. I am expecting to add more like 'java/io' in a `IO.cpp` in the future as well however.
> [native][refactor][NFC] move implementations out of `NativeImplementation.hpp`

- src/jllvm/object/Object.hpp
- tests/Execution/empty-string.java
We accidentally relied on a compiler extension in the code here by doing `sizeof` of a VLA. VLAs, as specified by C, have to have a size larger than 0, so UBSAN would raise an error if we effectively did `sizeof(T[0])`.
This PR just stops using VLAs.
> [object] fix UBSAN error when doing empty array size calculation

- src/jllvm/gc/GarbageCollector.cpp
- src/jllvm/object/ClassObject.cpp
- src/jllvm/object/ClassObject.hpp
This is a very simple implementation getting rid of the old introspection which was `O(|all_fields|)`. The new implementation is `O(instanceSize)` which is much smaller in practice. Besides that its also simply nicer code IMO.
> [object][gc] implement object introspection with simple mask

- src/jllvm/object/Object.hpp
- src/jllvm/vm/CMakeLists.txt
- src/jllvm/vm/NativeImplementation.cpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
- src/jllvm/vm/native/JDK.hpp
- src/jllvm/vm/native/Lang.hpp
- src/jllvm/vm/native/Security.cpp
- src/jllvm/vm/native/Security.hpp
- tests/Execution/thread.java
Despite being single threaded, we still want a `Thread` object representing that one thread we do have :) This is required by other code, most importantly `System.initPhase1`.
> [vm] create and initialize main `Thread` object

- src/jllvm/vm/JIT.cpp
The `llvm::orc::ConcurrentIRCompiler` wasn't properly being used anyways and always created and then destructed the `llvm::TargetMachine`. It contains rather large structures which are deallocated on destruction and would be allocated, constructed, destructed and deallocated for every compilation.
Using `SimpleCompiler` instead makes the code about 18% faster:
> [jit][NFC] use `llvm::orc::SimpleCompiler` to preserve the `llvm::TargetMachine`

- src/jllvm/gc/GarbageCollector.hpp
- src/jllvm/main/Main.cpp
- src/jllvm/object/ClassObject.hpp
- src/jllvm/support/CMakeLists.txt
- src/jllvm/support/FileUtils.cpp
- src/jllvm/support/FileUtils.hpp
- src/jllvm/vm/CMakeLists.txt
- src/jllvm/vm/NativeImplementation.cpp
- src/jllvm/vm/NativeImplementation.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
- src/jllvm/vm/native/IO.cpp
- src/jllvm/vm/native/IO.hpp
- src/jllvm/vm/native/JDK.cpp
- src/jllvm/vm/native/JDK.hpp
- src/jllvm/vm/native/Lang.hpp
- tests/Execution/runtime.java
- tests/Execution/system-properties.java
This PR includes all native methods required for `System.initPhase1` to complete successfully. These are part of a single commit mostly because they were not able to be tested independently or are really minor implementations not worth their own PR IMO.
Note that after this patch, startup time really goes up as around 100 classes any many many methods are compiled and execute before ever reaching `main`. This is the expected disadvantage of our single-tier fully optimizing JIT. Nevertheless, at this point in time, it only takes around a second in release builds on my machine.
> [vm] complete `System.initPhase1`

- src/jllvm/support/Encoding.cpp
- src/jllvm/support/Encoding.hpp
- src/jllvm/vm/NativeImplementation.cpp
- src/jllvm/vm/native/Lang.cpp
- src/jllvm/vm/native/Lang.hpp
- tests/System/print-unicode.java
This mainly required telling the system via a native method whether we are big endian or not. We apparently got the wrong idea that strings in Java are always big endian if UTF-16. Maybe this used to be true in older versions. Nowadays, they are apparently in native byte order and one simply has to tell the system the byte order.
With this patch we can now correctly display unicode characters in the output.
> [object][native] implement unicode output in `System.out`

- .github/workflows/pages.yml
- CMakeLists.txt
- docs/CMakeLists.txt
- docs/conf.py
- docs/index.md
- docs/requirements.txt
This PR is an initial draft at adding a deployable config for us to write any project documentation.
The documentation system proposed is using Sphinx together with MyST. The advantage of Sphinx is that it is extendable via plugins, has a rich ecosystem and also produces static HTML files that can be viewed offline without a running webserver.
The generation has been integrated with cmake and can be generated using the `docs`  target. 
It copies and creates a `docs/build/` directory where the output artifacts exist.
The advantage of MyST is that for 90% of tasks, one can simply use normal markdown, which, in my opinion, is more comfortable than RST. Yet when more advanced features of RST are required, it is possible to use these as well using special syntax. See https://mystmd.org/ as …
> [docs] Add initial documentation

- src/jllvm/support/NonOwningFrozenSet.hpp
- unittests/CMakeLists.txt
- unittests/NonOwningFrozenSetTests.cpp
This class allows creating a hashset over an array ref without taking ownership of the keys. The set is created and then frozen upon construction, making it not possible to add any more keys to the set. The set additionally preserves insertion order.
One of the main features of the set is the support for heterogeneous lookup, making it possible to do lookups with any type with a compatible implementation to the key type.
Main use case for this set is in use of the `ClassObject` class for field and method lookup. It is therefore also a standard layout type.
> [support] add `NonOwningFrozenSet`

- src/jllvm/materialization/ByteCodeLayer.cpp
- src/jllvm/materialization/ByteCodeLayer.hpp
- src/jllvm/materialization/CodeGeneratorUtils.cpp
- src/jllvm/materialization/CodeGeneratorUtils.hpp
- src/jllvm/object/ClassLoader.cpp
- src/jllvm/object/ClassLoader.hpp
- src/jllvm/object/ClassObject.cpp
- src/jllvm/object/ClassObject.hpp
- src/jllvm/support/NonOwningFrozenSet.hpp
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/native/Lang.hpp
- unittests/CMakeLists.txt
- unittests/NonOwningFrozenSetTests.cpp
These new methods 1) make use of the new frozen set for more convenient lookup 2) are more generic allowing arbitrary predicates to be used to search. Looking up either instance or static fields are particular often used functions and have been given their own methods.
Additionally, to make the result of these methods more useful, `Method` now has a pointer to its containing `ClassObject`.
Depends on https://github.com/JLLVM/JLLVM/pull/184
> [object][NFC] create and use better methods for method and field lookup

- src/jllvm/gc/GarbageCollector.cpp
- src/jllvm/gc/RootFreeList.hpp
- src/jllvm/object/Object.hpp
- src/jllvm/vm/InteropHelpers.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
- src/jllvm/vm/native/JDK.hpp
- src/jllvm/vm/native/Lang.cpp
- unittests/GarbageCollectorTests.cpp
Previously, any API taking a `T*` would require explicitly casting a `GCRootRef`, either via `static_cast` or `.address()` to get the address of the contained object. This made using `GCRootRef` less comfortable then it has to be and made its behaviour differ to `Object*` from a user perspective in a few places. Worst of all, wanting to avoid these explicit casts would often lead to APIs taking `GCRootRef<T>` parameters instead of `T*` parameters despite the latter being the better more generic choice if no GCs can occur during those function calls.
This PR therefore makes the conversion operator to 'T*' implicit. The advantages of this is the useability in all the previously mentioned scenarios. The disadvantages are that one could deem it as non-obvious "magic" and the potential for …
> [object][NFC] make `GCRootRef` implicitly convertible to `T*`

- src/jllvm/object/ClassObject.hpp
- src/jllvm/object/Object.hpp
- src/jllvm/vm/InteropHelpers.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
- src/jllvm/vm/native/Lang.hpp
These classes serve as strongly typed wrappers around a `Field*` allowing more convenient access to a field from C++ code. Access is modeled via the call operator, returning a reference to either the static field or the instance field of an object.
The most important use-case for these is for native interop. Previously, we were forced to create a C++ type mirroring the Java object layout to be able to access any of its fields conveniently. This creates a tight coupling between the C++ type and the corresponding class file which was very fragile as the layout can easily change.
With these new classes, we can instead search for the field in question and use it directly. The only coupling remaining are the field name and type which are less fragile than the memory layout of the containing …
> [object][NFC] add `InstanceFieldRef` and `StaticFieldRef` concepts

- src/jllvm/vm/InteropHelpers.hpp
- src/jllvm/vm/NativeImplementation.hpp
- src/jllvm/vm/VirtualMachine.hpp
- src/jllvm/vm/native/IO.cpp
- src/jllvm/vm/native/IO.hpp
- src/jllvm/vm/native/JDK.hpp
- src/jllvm/vm/native/Lang.hpp
- src/jllvm/vm/native/Security.hpp
Refactored the CRTP implementation for stateful `ModelBase` subclasses to use the simpler templated `State` approach.
> [native] refactor `ModelBase` and subclasses to use `State` template

- .github/workflows/llvm-cache.yml
A nightly LLVM builder ensures that 1) our caches are always up-to-date to make CI run FAST, regardless of whether as a PR, the main branch or the merge queue and that 2) even if GitHub updates their runner images with newer compiler versions, that we have a cache ready sooner.
Fixes https://github.com/JLLVM/JLLVM/issues/193
> [CI] Add nightly LLVM builder

- src/jllvm/class/ClassFile.cpp
- src/jllvm/class/ClassFile.hpp
- src/jllvm/class/Descriptors.hpp
- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/materialization/ByteCodeLayer.cpp
- src/jllvm/materialization/ByteCodeLayer.hpp
- src/jllvm/materialization/CodeGenerator.cpp
- src/jllvm/materialization/CodeGenerator.hpp
- src/jllvm/materialization/CodeGeneratorUtils.cpp
- src/jllvm/materialization/CodeGeneratorUtils.hpp
- src/jllvm/materialization/JNIImplementationLayer.cpp
- src/jllvm/materialization/JNIImplementationLayer.hpp
- src/jllvm/object/ClassLoader.cpp
- src/jllvm/object/ClassLoader.hpp
- src/jllvm/object/ClassObject.cpp
- src/jllvm/object/ClassObject.hpp
- src/jllvm/vm/JIT.hpp
- src/jllvm/vm/StringInterner.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
- src/jllvm/vm/native/Lang.hpp
The new classes have the large advantage of being strongly typed and giving us a lot of correctness by construction. There is also no longer a need for an explicit parsing step and it is possible to nicely compose constructors from parameters, forming the exact descriptor without the need for string manipulation.
Depends on https://github.com/JLLVM/JLLVM/pull/190
> [refactor][NFC] Refactor entire codebase to use new descriptor class

- src/jllvm/materialization/CodeGenerator.cpp
- src/jllvm/materialization/CodeGeneratorUtils.hpp
- tests/Execution/exception-handling-stack-type-mismatch.j
The code in the `OperandStack` incorrectly set the LLVM type of the bottom most operand as well when calling `setHandlerStack`. The method was only used during generation of the exception handling chain which shouldn't affect the operand stack at all as compilation continues afterward as usual.
This PR fixes that issue by removing the `setHandlerStack` method, as it in my opinion is oddly named, and not storing an LLVM type to the operand stack.
> [codegen] Fix operand stack type mismatch after exception handling code

- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/materialization/ByteCodeCompileUtils.cpp
- src/jllvm/materialization/ByteCodeCompileUtils.hpp
- src/jllvm/materialization/CodeGeneratorUtils.cpp
- src/jllvm/materialization/JNIImplementationLayer.cpp
- src/jllvm/materialization/LambdaMaterialization.hpp
Code previously had a lot of code duplication which made applying changes to how ABI attributes are applied a lot more difficult as it required searching all over the codebase. This PR therefore creates new functions that are called on any call instruction and function to apply attributes important for any methods specific to implementing Java to the call or function.
Additionally, it documents and works around a bug that has in the past caused us many ABI issues with passing integers around. During investigations, I found out that the `gc.statepoint` intrinsic, which calls are converted to, to implement parseable stacks for the GC, are currently not properly created with argument attributes, erasing them all instead. A PR was posted upstream to fix it but won't be part of LLVM until at …
> [codegen][NFC] Refactor ABI sensitive LLVM attribute application 

- src/jllvm/materialization/CodeGenerator.cpp
- src/jllvm/materialization/CodeGenerator.hpp
- src/jllvm/vm/VirtualMachine.cpp
- tests/Execution/faload-fastore.java
- tests/Execution/iaload-iastore.java
- tests/Execution/instance-fields.java
- tests/Execution/interface-methods.java
- tests/Execution/invoke-virtual.java
- tests/Execution/monitor-enter-exit.java
- tests/Execution/object-array-ops.java
This PR implements the proper throwing of  `NullPointerException` for JVM instructions dealing with reference types where such behavior is required.
Fixes: #154
> [codegen] implement throwing of `NullPointerException` for ops operating on reference types

- .github/actions/llvm-build/action.yml
- .github/workflows/builds.yml
- .github/workflows/llvm-cache.yml
- CMakeLists.txt
- src/jllvm/materialization/CMakeLists.txt
- src/jllvm/unwind/CMakeLists.txt
- src/jllvm/vm/CMakeLists.txt
A shared library build has the advantage that they are linked and that one is able to tell the linker that undefined references are not allowed. Unlike the static build this ensures that we have clean modules that do not depend on any other modules, forcing us to have a cleaner non-monolithic design with less coupling.
Fixes https://github.com/JLLVM/JLLVM/issues/203
> [CI] Add shared builds builder

- src/jllvm/materialization/ClassObjectStubCodeGenerator.cpp
- src/jllvm/materialization/ClassObjectStubDefinitionsGenerator.cpp
- src/jllvm/materialization/CodeGeneratorUtils.cpp
- src/jllvm/materialization/CodeGeneratorUtils.hpp
- src/jllvm/object/ClassLoader.cpp
- src/jllvm/object/ClassObject.cpp
- src/jllvm/object/ClassObject.hpp
- src/jllvm/vm/ClassObjectStubImportPass.cpp
This was the last method using `returnConstantForClassObject` from `LazyClassLoaderHelper` which could now be removed. To reduce a lot of the boilerplate required, a few methods were refactored and put into the `ByteCodeCompileUtils.hpp` header for reuse.
Depends on https://github.com/JLLVM/JLLVM/pull/199 and https://github.com/JLLVM/JLLVM/pull/202
> [codegen] Move class object loading to the new stub generator

- src/jllvm/materialization/CodeGenerator.cpp
- src/jllvm/materialization/CodeGenerator.hpp
- src/jllvm/vm/VirtualMachine.cpp
- tests/Execution/array-index-out-of-bounds-exception-errror.java
- tests/Execution/faload-fastore.java
- tests/Execution/iaload-iastore.java
- tests/Execution/llvm-miscompile.java
This PR implements the proper throwing of `ArrayIndexOutOfBoundsException` for JVM instructions dealing with reading from and writing to arrays.
Fixes: #155
> [codegen] implement throwing of `ArrayIndexOutOfBoundsException` for ops reading from and writing to arrays

- src/jllvm/materialization/CodeGenerator.cpp
- src/jllvm/materialization/CodeGenerator.hpp
- src/jllvm/vm/VirtualMachine.cpp
- tests/Execution/negative-array-size-exception-errror.java
This PR implements the proper throwing of NegativeArraySizeException for JVM instructions dealing with creating arrays.
Fixes: #156
> [codegen] implement throwing of `NegativeArraySizeException` for ops creating arrays

- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/vm/NativeImplementation.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
This PR removes the optimizations in exception handling for already loaded classes made impossible by the removal of `LazyClassLoaderHelper` and moves `ModelState` next to  `ModelBase`.
> [refactor] remove impossible optimization and refactor `ModelState`

- src/jllvm/class/ByteCodeIterator.hpp
- src/jllvm/class/ClassFile.cpp
- src/jllvm/class/ClassFile.hpp
- src/jllvm/compiler/ByteCodeCompileUtils.cpp
- src/jllvm/compiler/ByteCodeCompileUtils.hpp
- src/jllvm/compiler/ClassObjectStubMangling.cpp
- src/jllvm/compiler/ClassObjectStubMangling.hpp
- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/compiler/CodeGenerator.hpp
- src/jllvm/compiler/CodeGeneratorUtils.cpp
- src/jllvm/compiler/CodeGeneratorUtils.hpp
- src/jllvm/compiler/Compiler.cpp
- src/jllvm/compiler/Compiler.hpp
- tests/Compiler/osr-frames.j
- tests/tools/jllvm-jvmc/invalid.java
- tools/jllvm-jvmc/Opts.td
- tools/jllvm-jvmc/main.cpp
On-Stack-Replacement (OSR) methods are special versions of a method which start at a specific byte offset that possibly isn't 0. The use-case for such a method is in tiered compilation: Given an execution of a method (either JIT or Interpreter), it may wish to continue execution within the JIT. An OSR method for a requested offset where execution should continue can then be compiled and used.
To facilitate changing the frames of one execution to the new JIT compiled frame, the abstract machine state has to be transferred as well. In the case of the JVM, these are the local variables, the operand stack and the program counter. The latter is already baked into the compilation while the operand and local variables can be passed as an array of `int64_t`s as parameters respectively. The exact …
> [compiler] Implement compilation of OSR method

- src/jllvm/gc/GarbageCollector.cpp
- src/jllvm/unwind/CMakeLists.txt
- src/jllvm/unwind/Unwinder.cpp
- src/jllvm/unwind/Unwinder.hpp
- src/jllvm/vm/native/JDK.cpp
This uses the low level API of `libunwind` rather than the Itanium ABIs as it is generally more powerful. The unwinding API gained one new function called `callerFrame` which can be used to get the caller frame. It is also used to implement `unwindStack` which remains the only function that can create frames.
> [unwind] Port unwinder code to our fork

- src/jllvm/class/ClassFile.hpp
- src/jllvm/compiler/ClassObjectStubCodeGenerator.cpp
- src/jllvm/object/ClassLoader.cpp
- src/jllvm/object/ClassObject.cpp
- src/jllvm/object/ClassObject.hpp
- src/jllvm/vm/VirtualMachine.cpp
- tests/Execution/static-final-fields-optimization.java
This PR adds an optimization for for accessing static final fields of non-reference types.
When generating code for every such field, if the class object is already initialized, a static constant within the LLVM IR is created with the value of the field. In all further accesses that value will be used removing the need to load from memory.
Fixes: #10
> [compiler] Add optimization for static final fields

- .clang-tidy
- src/jllvm/compiler/ClassObjectStubCodeGenerator.cpp
- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/compiler/CodeGenerator.hpp
- src/jllvm/compiler/Compiler.cpp
- src/jllvm/main/Main.cpp
- src/jllvm/materialization/JNIImplementationLayer.cpp
- src/jllvm/materialization/LambdaMaterialization.hpp
- src/jllvm/unwind/Unwinder.cpp
- src/jllvm/unwind/Unwinder.hpp
- src/jllvm/vm/CMakeLists.txt
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/JIT.hpp
- src/jllvm/vm/StackMapRegistrationPlugin.cpp
- src/jllvm/vm/StackMapRegistrationPlugin.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
- tests/Compiler/osr-frames.j
- tests/Execution/deopt-smaller-than-pointer.j
This is the very first mechanism making use of OSR. This PR completely replaces the manual checks of `activeException` entirely with a system more closely matching how exception handling works in languages like C++ with the addition of JIT and OSR.
The new exception handling now works through the use of "deoptimization" operands in LLVM. These are operands that are put into the stackmap and can be read by the unwinder, similarily to how GC pointers are currently read. When an exception is thrown, we unwind the stack and search for the frame of a Java method that contains an exception handler for the thrown exception. If found, the deoptimization operands are used to read the local variables in that frame and transfer them to a new JIT compiled OSR frame that starts at the exception …
> [vm] Implement On-Stack-Replacement on `throw`

- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/compiler/CodeGenerator.hpp
- src/jllvm/compiler/CodeGeneratorUtils.cpp
- src/jllvm/compiler/CodeGeneratorUtils.hpp
- src/jllvm/compiler/Compiler.cpp
This PR changes `ByteCodeTypeInfo` from an in-out parameter of the constructor of `ByteCodeTypeChecker` to a return value of `checkAndGetTypeInfo`.
> [refactor] move `ByteCodeTypeInfo` into `ByteCodeTypeChecker`

- .github/actions/dependencies/action.yml
- .github/workflows/builds.yml
Since we're using C++20 it is more important to use newer compilers than usual. In particular, we've had to deal with bugs in various C++20 features such as https://godbolt.org/z/PzhMTYG3b which are difficult to workaround and very very VERY difficult to debug. This PR therefore switches our GCC version to GCC 13 which is the newest shipped on GitHub actions.
> [CI] upgrade to GCC 13

- src/jllvm/materialization/LambdaMaterialization.hpp
This method has been dead since the removal of the `LazyClassLoadHelper` and no longer serves any purpose, nor will serve any purpose in the foreseeable future
> [materialization][NFC] Remove `CppToLLVMType::getConstant`

- src/jllvm/compiler/ByteCodeCompileUtils.cpp
- src/jllvm/compiler/ByteCodeCompileUtils.hpp
- src/jllvm/compiler/ClassObjectStubCodeGenerator.cpp
- src/jllvm/compiler/ClassObjectStubCodeGenerator.hpp
- src/jllvm/compiler/ClassObjectStubMangling.cpp
- src/jllvm/compiler/ClassObjectStubMangling.hpp
- src/jllvm/llvm/ClassObjectStubImportPass.cpp
- src/jllvm/materialization/ClassObjectStubDefinitionsGenerator.cpp
- src/jllvm/materialization/JNIImplementationLayer.cpp
- src/jllvm/vm/JIT.cpp
- tests/Compiler/method-metadata.j
Class objects and pointers to globals have so far been embedded in IR with their address. This is undesirable for many reasons, some described in https://github.com/JLLVM/JLLVM/issues/196. This PR replaces the pointer embedding with proper external global variables which the JIT linker later resolves to the actual class object and method.
Depends on https://github.com/JLLVM/JLLVM/pull/224
> [vm][compiler] Introduce globals for class objects and methods

- src/jllvm/unwind/Unwinder.hpp
Due to what looks like a bug and regression in Clang 17 it is currently not possible to compile JLLVM with Clang 17 or newer. After upgrading my compiler today I was immediately hit with build failures.
This PR worksaround the Clang bug and leaves a link to the issue tracker to 1) track the issue and 2) remove it one day if we stop supporting Clang 17
> [unwinder] Workaround Clang 17 build regression

- src/jllvm/support/Bytes.hpp
- src/jllvm/unwind/CMakeLists.txt
- src/jllvm/unwind/Unwinder.hpp
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/JIT.hpp
- src/jllvm/vm/StackMapRegistrationPlugin.cpp
- src/jllvm/vm/StackMapRegistrationPlugin.hpp
This class is used to represent the location of a value within a frame as are seen in the stackmap when using `deopt` operand bundles or using GCs. This class abstracts the precise mechanism used to read the value in the frame and simply offers a convenient 'read' API.
> [unwinder] Add 'FrameValue' class

- src/jllvm/class/Descriptors.hpp
- src/jllvm/compiler/ByteCodeCompileUtils.cpp
- src/jllvm/compiler/ByteCodeCompileUtils.hpp
- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/compiler/CodeGenerator.hpp
- src/jllvm/compiler/CodeGeneratorUtils.cpp
- src/jllvm/compiler/CodeGeneratorUtils.hpp
- src/jllvm/compiler/Compiler.cpp
- tests/Compiler/locals-deopt-types.j
- tests/Compiler/locals-types-dataflow-merge.j
The precise type of local variables is required to properly read them out when creating deoptimization state on calls. So far, `ptr addrspace(1)` has been used for this purpose, but this is problematic and has actually led to bugs as LLVM later thought that these were GC pointers. Not using `ptr addrspace(1)` is also incorrect as actual GC pointers still need to be tracked and kept alive by the deopt.
This PR therefore extends the `ByteCodeTypeChecker` to also calculate the local variables at the start of all basic blocks and adds a `LocalVariables` class, that similar to `OperandStack`, tracks the current type of a local variable throughout compilation. These are also used to generate appropriate loads and stores.
> [compiler] Precisely track types of local variables

- .github/actions/llvm-build/action.yml
The default `actions/cache` action does not save the cache if the workflow as a whole failed. This is annoying in our case as test failures in JLLVM should not affect cacheability of the LLVM build. Using explicit save and restore actions fixes this.
Fixes https://github.com/JLLVM/JLLVM/issues/194
> [CI] Cache LLVM build immediately upon completion

- src/jllvm/gc/CMakeLists.txt
- src/jllvm/gc/GarbageCollector.cpp
- src/jllvm/gc/GarbageCollector.hpp
- src/jllvm/unwind/Unwinder.hpp
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/StackMapRegistrationPlugin.cpp
- src/jllvm/vm/StackMapRegistrationPlugin.hpp
Derived pointers are pointers which are potentially offset from a pointer to an object, the base pointer, by some amount. After relocation, the offset must be preserved by relocating the derived pointer through applying the offset to the relocated base pointer.
This patch implements the required support for relocating such derived pointers within our GC. LLVMs stackmap supplies us with a pair of `(basePtr, derivedPtr)`s which can be used to calculate the offset for the relocation. A new `WriteableFrameValue` class was introduced on-top of the `FrameValue` class to support writing to frame values making the GC code simpler. Last, I had to also remove the `ObjectRepr` class as I didn't want to expose it as a public class but also wanted `WriteableFrameValue` to be strongly typed. I believe …
> [gc] add support for relocating derived pointers

- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/compiler/CodeGenerator.hpp
- src/jllvm/gc/CMakeLists.txt
- src/jllvm/gc/GarbageCollector.cpp
- src/jllvm/gc/GarbageCollector.hpp
- src/jllvm/unwind/Unwinder.hpp
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/StackMapRegistrationPlugin.cpp
- src/jllvm/vm/StackMapRegistrationPlugin.hpp
- tests/Compiler/elide-deopt.j
The local variables in the deopt operand bundle are only read out and required when the instruction is within an exception handler. In all other cases it is possible to elide these operands to improve code-generation.
> [compiler] remove redundant deopt operands

- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/compiler/CodeGenerator.hpp
- tests/Compiler/exceptions-missing-deopt.j
Deoptimization states should be added to every call within a java method from which the stack may be unwound. Since these methods may throw an exception (e.g. out of memory) or generate a stacktrace, deoptimization state should be added to at the very least be able to retrieve the corresponding JVM bytecode.
> [compiler] add missing deoptimnization state to builtin exceptions

- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/compiler/CodeGenerator.hpp
- tests/Compiler/osr-frames.j
This PR removes `generateHandlerChain` and `m_alreadyGeneratedHandlers` from `CodeGenerator`, which have become unnecessary due to exception handling being done via deopts.
Fixes: #243
> [codegen] Remove exception hanlder chain

- src/jllvm/compiler/ByteCodeCompileUtils.cpp
- src/jllvm/compiler/ByteCodeCompileUtils.hpp
- src/jllvm/compiler/CMakeLists.txt
- src/jllvm/compiler/Compiler.cpp
- src/jllvm/materialization/JNIImplementationLayer.cpp
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/JIT.hpp
- src/jllvm/vm/StackMapRegistrationPlugin.cpp
- src/jllvm/vm/StackMapRegistrationPlugin.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/native/JDK.cpp
- tests/Compiler/method-metadata.j
Metadata associated with Java code has gotten scattered over time: We currently have the `JavaMethodMetadata` for class objects and methods, `DeoptEntry`s for reading local variables and the bytecode offset.
This PR consolidates all metadata into one datastructure again and creates the following distinction:
* `JavaMethodMetadata` is now used for all metadata that is relevant for the whole method. It additionally contains extra metadata that can be specialized for JITted methods, native methods and in the future interpreter methods.
* Per-PC metadata such as the Java bytecode offset, or the `FrameValue`s for local variables at a given callsite. This mapping is part of a mapping contained within the JIT data of `JavaMethodMetadata`.
All low-level metadata access one would ever require …
> [compiler] Refactor Java method metadata

- src/jllvm/vm/CMakeLists.txt
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/JIT.hpp
- src/jllvm/vm/JavaFrame.cpp
- src/jllvm/vm/JavaFrame.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
- src/jllvm/vm/native/JDK.cpp
This class is a specialization of `UnwindFrame` that offers convenient methods to gather Java-specific info about a frame being unwound. Most importantly, it serves as a common API for when adding new execution implementations such as an interpreter.
> [vm][NFC] Introduce `JavaFrame` class

- src/jllvm/class/ByteCodeIterator.hpp
- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/compiler/CodeGeneratorUtils.cpp
- src/jllvm/vm/Interpreter.cpp
This PR changes the API of constructing a `ByteCodeIterator`  by making to more intuitive and less prone to misuse.
> [refactor] Make `ByteCodeIterator` constructor more intuitive

- src/jllvm/vm/Interpreter.cpp
- src/jllvm/vm/Interpreter.hpp
- tests/Execution/iadd.java
This PR implements the basic integer operations for manipulating the operand stack and local variables and `iadd`. This makes it possible to first execute some integer instructions such as the `iadd` test case mostly from within the interpreter.
Most importantly, the patch required adding methods to `InterpreterContext` for manipulating the operand stack and local variables.
> [interpreter] add basic integer stack and variable instructions

- src/jllvm/gc/GarbageCollector.cpp
- src/jllvm/gc/GarbageCollector.hpp
- src/jllvm/gc/RootFreeList.cpp
- src/jllvm/gc/RootFreeList.hpp
- src/jllvm/object/ClassLoader.hpp
- src/jllvm/vm/VirtualMachine.cpp
There are other heaps such as the `ClassLoader` containing Java objects which may refer to Java objects on the GC. To be able to mark such objects as reachable and update references as they are relocated, a new interface is added in this PR called `RootProvider` which adds convenient methods for adding callbacks for root traversal. As a POC, the class objects in the `ClassLoader` are added as root sets. While related code was being touched, some needless occurrences of `void**` were also removed in the code (yay to more typesafety).
Sadly, I failed to write a meaningful test as part of this PR as we are currently incapable of producing scenarios where `ClassObject`s point to Java objects in the GC heap with our current native methods in `Class`.
A later PR will use this functionality to …
> [gc] add new interface for adding external roots to the GC

- src/jllvm/compiler/ByteCodeCompileUtils.cpp
- src/jllvm/compiler/ByteCodeCompileUtils.hpp
- src/jllvm/compiler/ClassObjectStubMangling.cpp
- src/jllvm/compiler/ClassObjectStubMangling.hpp
- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/compiler/CodeGenerator.hpp
- src/jllvm/compiler/Compiler.cpp
- src/jllvm/compiler/Compiler.hpp
- src/jllvm/materialization/ByteCodeCompileLayer.cpp
- src/jllvm/materialization/ByteCodeCompileLayer.hpp
- src/jllvm/materialization/ByteCodeOSRCompileLayer.cpp
- src/jllvm/materialization/ByteCodeOSRCompileLayer.hpp
- src/jllvm/materialization/ClassObjectStubDefinitionsGenerator.cpp
- src/jllvm/materialization/ClassObjectStubDefinitionsGenerator.hpp
- src/jllvm/vm/JIT.cpp
- tests/Compiler/string-globals.j
- tools/jllvm-jvmc/main.cpp
This PR removes the embedding of pointers to strings interned at compile time with proper external global variables which the JIT linker later resolves.
This in term removes the need for `StringInterner` for the generation of LLVM IR and all associated facets.
Altogether reducing coupling and leading to a cleaner design.
> [vm][compiler] Introduce globals for interned strings

- src/jllvm/object/ClassObject.cpp
- src/jllvm/object/ClassObject.hpp
- tests/Execution/invoke-interface-superinterfaces.j
The JVM spec states that as a last step, the method should be resolved in any of the interface methods as long as it is not static or private. This was previously not done for unknown reasons.
This patch implements the missing lookup step. While touching the code, `getMethod` was redefined to only do a lookup in the current class, as that is the more common operation. The previous `getMethod` was renamed to `getMethodSuper`
> [object] Add missing superinterfaces lookup in interface method resolution

- src/jllvm/vm/Interpreter.cpp
- src/jllvm/vm/Interpreter.hpp
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/JavaFrame.cpp
- src/jllvm/vm/JavaFrame.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
- src/jllvm/vm/native/Lang.hpp
- tests/Execution/interpreter-gc.j
This PR adds support for the 'new' instruction, making it possible to create Java objects from within the interpreter. Since Java objects are now in the interpreter context, garbage collection support was added to the interpreter as well. This is implemented using the new `RootProvider` API, making it possible to add the interpreter's operand stack and local variables as roots for marking and relocation.
> [interpreter] add support for `new`

- src/jllvm/support/BitArrayRef.hpp
- src/jllvm/vm/Interpreter.hpp
- src/jllvm/vm/JavaFrame.cpp
- src/jllvm/vm/JavaFrame.hpp
- src/jllvm/vm/VirtualMachine.cpp
- unittests/BitArrayRefTests.cpp
- unittests/CMakeLists.txt
These classes can be used to conveniently interpret external memory as a bitset, allowing convenient methods to access individual bits.
> [support] Add `[Mutable]BitArrayRef` classes

- src/jllvm/gc/GarbageCollector.cpp
- src/jllvm/unwind/Unwinder.hpp
When the base-pointer is relocated prior to the derived pointer then the derived pointer cannot be relocated as 1) no mapping exists for the relocated base pointer and 2) no offset between the derived and base pointer can be determined. This PR fixes that issues by doing a partition of the frame values, moving base pointer entries AFTER the derived pointer entries
> [gc] Fix bug where base-pointer is relocated prior to derived

- .github/workflows/llvm-cache.yml
This was missed when upgrading from GCC 10 to GCC 13 causing LLVM builds with GCC 10 to be regularly built rather than GCC 13
> [ci] use GCC 13 in LLVM cron job

- src/jllvm/compiler/ByteCodeCompileUtils.cpp
- src/jllvm/compiler/Compiler.cpp
- src/jllvm/vm/CMakeLists.txt
- src/jllvm/vm/Interpreter.cpp
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/JIT.hpp
- src/jllvm/vm/JavaFrame.cpp
- src/jllvm/vm/JavaFrame.hpp
- src/jllvm/vm/OSRState.cpp
- src/jllvm/vm/OSRState.hpp
- tests/Compiler/osr-frames.j
This class is meant to be an abstraction representing the abstract machine state of a given target, adding nicer named "constructors" and generic getter functions. Most importantly it internally builds up the internal datastructure used in the calling convention to pass the given state.
> [vm] Introduce `OSRState` class

- src/jllvm/compiler/ByteCodeCompileUtils.hpp
- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/materialization/CMakeLists.txt
- src/jllvm/materialization/InterpreterEntry.cpp
- src/jllvm/materialization/InterpreterEntry.hpp
- src/jllvm/materialization/InterpreterOSRLayer.cpp
- src/jllvm/materialization/InterpreterOSRLayer.hpp
- src/jllvm/materialization/JIT2InterpreterLayer.cpp
- src/jllvm/support/BitArrayRef.hpp
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/JIT.hpp
- src/jllvm/vm/JavaFrame.cpp
- src/jllvm/vm/JavaFrame.hpp
- src/jllvm/vm/OSRState.cpp
- src/jllvm/vm/OSRState.hpp
- src/jllvm/vm/StackMapRegistrationPlugin.cpp
- tests/Compiler/elide-deopt.j
- tests/Compiler/locals-deopt-types.j
- tests/Compiler/locals-types-dataflow-merge.j
- unittests/BitArrayRefTests.cpp
So far it has only been possible to perform OSR into a JITted frame. This PR also adds the capability to OSR into the interpreter and switches the exception handler to do so by default.
This is achieved by creating an `InterpreterOSRLayer` which compiles a version of the interpreter entry stub which initializes the abstract machine state from an `OSRState` instance.
> [materialization] Implement OSR to interpreter frames

- src/jllvm/class/ClassFile.cpp
- src/jllvm/class/ClassFile.hpp
- src/jllvm/materialization/ClassObjectStubDefinitionsGenerator.cpp
- src/jllvm/materialization/ClassObjectStubDefinitionsGenerator.hpp
- src/jllvm/object/ClassLoader.cpp
- src/jllvm/object/ClassLoader.hpp
- src/jllvm/object/StringInterner.cpp
- src/jllvm/object/StringInterner.hpp
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/JIT.hpp
- src/jllvm/vm/OSRState.hpp
- src/jllvm/vm/VirtualMachine.cpp
- tests/Execution/constant-value-fields.j
- tools/jllvm-jvmc/main.cpp
This PR adds support for reading the `ConstantValue` attribute of `FieldInfo` structs of classfiles. It also implements the required behavior of the value of static fields with the attribute to have their initial value set to the value indicated by the attribute.
> [vm] Add support for handling `ConstantValue` attribute of fields

- src/jllvm/vm/Interpreter.cpp
- src/jllvm/vm/Interpreter.hpp
These operations are the few operations that operate on raw memory rather than requiring a specific typed operand. Most importantly, these behave different in the spec depending on whether the values are `long` or `double` or others. In a previous PR we started using two operand stack slots for `long` and `double` (which is also supported by the `Code` attribute), making the operations in "Form 1" as the spec calls it, identical to when operating on `double` or `long`.
> [interpreter] Implement stack operations

- src/jllvm/CMakeLists.txt
- src/jllvm/compiler/CMakeLists.txt
- src/jllvm/compiler/ClassObjectStubCodeGenerator.cpp
- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/compiler/CodeGenerator.hpp
- src/jllvm/debuginfo/CMakeLists.txt
- src/jllvm/debuginfo/TrivialDebugInfoBuilder.cpp
- src/jllvm/debuginfo/TrivialDebugInfoBuilder.hpp
- src/jllvm/materialization/CMakeLists.txt
- src/jllvm/materialization/JIT2InterpreterLayer.cpp
- src/jllvm/materialization/JNIImplementationLayer.cpp
- src/jllvm/materialization/LambdaMaterialization.hpp
Various methods for generating stubs with LLVM IR where either missing debug info or repeating lots of code to construct the minimum amount of debug info required.
This PR extracts the `TrivialDebugInfoBuilder` out of code generation and makes it available as class and library for reuse.
Looking at the callstack in the debugger is also improved by this PR as methods that previously didn't emit debug info now do.
> [debuginfo] Extract and consistently use `TrivialDebugInfoBuilder`

- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/object/Object.hpp
- src/jllvm/vm/native/Lang.cpp
- src/jllvm/vm/native/Lang.hpp
- tests/Execution/object-clone.java
This PR implements `Object.clone` to be able to clone array required by #255.
It also fixes a bug in loading the class object for `anewarray`  in `CodeGenerator`.
> [native] Implement `Object.clone`

- src/jllvm/class/ByteCodeIterator.hpp
- src/jllvm/vm/Interpreter.cpp
This PR reuses the `MultiTypeImpls` class to implement the basic arithmetic operations generically on all types supported by the JVM. Exceptions to this rule are division and remainder, which have differing semantics in the case of `rhs == 0` among other things.
I opted not to implement throwing an `ArithmeticException` yet as it is not done in the JIT yet either. Implementing both at the same time makes the most sense to me.
> [interpreter] implement arithmetic operations

- src/jllvm/materialization/JNIImplementationLayer.cpp
- src/jllvm/vm/JIT.cpp
The current implementation effectively "leaks" a local frame if an exception passes through a JNI frame as the `jllvm_pop_local_frame` function is never called. This PR fixes that by generating LLVM IR that does proper exception handling to call `jllvm_pop_local_frame`. It also required adding a personality function which is capable of calling our exception handling code. For now, we simply reuse the personality supplied by our C++ toolchains.
Fixes https://github.com/JLLVM/JLLVM/issues/246
> [JNI] Cleanup local frame on exception

- src/jllvm/class/Descriptors.hpp
- src/jllvm/object/ClassLoader.cpp
- src/jllvm/object/ClassObject.hpp
- src/jllvm/vm/Interpreter.cpp
- src/jllvm/vm/Interpreter.hpp
- src/jllvm/vm/native/JDK.hpp
This PR implements accessing both instance and static fields of Java Objects. The implementation simply finds the given field in the class object and then uses memcpy to load the corresponding value according to the descriptor. The address is either formed via an offset from the object if an instance field or directly returned by the field if static.
> [interpreter] Implement field accesses

- src/jllvm/class/ByteCodeIterator.hpp
- src/jllvm/vm/Interpreter.cpp
This PR implements all the various return instructions used to return from a method. While most could be handled generically, `ireturn` and plain `return` required special implementation as they behave differently from the others. The former does special conversions for types other than `int` while the latter does not return a value at all.
We do not yet implement `synchronized` methods, so no special handling was added.
> [interpreter] Implement return instructions

- src/jllvm/class/ByteCodeIterator.hpp
- src/jllvm/class/ClassFile.cpp
- src/jllvm/class/ClassFile.hpp
- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/compiler/CodeGenerator.hpp
- src/jllvm/compiler/CodeGeneratorUtils.cpp
- src/jllvm/compiler/CodeGeneratorUtils.hpp
- src/jllvm/compiler/Compiler.cpp
- src/jllvm/vm/VirtualMachine.cpp
- tests/Compiler/locals-types-dataflow-merge.j
The bytecode type checker was only propagating types of local variables to exception handler at the start of the exception handler. This would lead to incorrectly deducing a type of a local variable where it should be inaccessible instead. This PR fixes the issue by propagating local variable types for every operation that may throw an exception. As a side-effect of this change, `Code` now also builds an interval tree for conveniently and quickly finding all exception handlers for a given bytecode offset.
> [codegen] Correctly deduce local variable types in exception handlers

- src/jllvm/class/ByteCodeIterator.hpp
- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/gc/GarbageCollector.hpp
- src/jllvm/materialization/JNIImplementationLayer.cpp
- src/jllvm/object/Object.hpp
- src/jllvm/vm/Interpreter.cpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
- tests/Compiler/exceptions-missing-deopt.j
This PR implements all array operations but `multianewarray` and `newarray`. As many of these operations are capable of throwing different exceptions where the JIT compiler already uses nice messages, the methods creating these exception objects and throwing them were moved to their own methods in `VirtualMachine` and reused. Since the version of them throwing is nicer and easier to use, the JIT code was also adjusted to expect these methods to throw the exception rather than create the exception object.
> [interpreter] Implement almost all array operations

- src/jllvm/object/ClassObject.cpp
- tests/Execution/instanceof.java
This PR fixes the bug where multidimensional array were not considered instances of Object arrays.
It also makes arrays be considered instances of the interfaces defined in the spec.
> [object] Fix bug in `wouldBeInstanceOf` for arrays

- src/jllvm/vm/Interpreter.cpp
- src/jllvm/vm/Interpreter.hpp
- tests/Execution/interpreter-wide-putstatic-bug.j
The implementations of field access methods made use of `pushRaw` and `popRaw` as the types being operated on are runtime dependent on the type of the field being accessed. However, using these methods is dangerous, as this requires manually handling wide types such as `long` and `double`. This has happened in the implementations of `putstatic` and `putfield` where the order of `popRaw` calls was incorrect, leading to always storing 0 in the field.
This PR fixes that issue by adding new overloads for `push` and `pop` which take a field descriptor as parameter. This adds a safe and convenient version of `pop` and `raw` while still being capable of specifying types at runtime.
> [interpreter] fix bug in `put*` of wide types

- src/jllvm/class/ByteCodeIterator.cpp
- src/jllvm/class/ByteCodeIterator.hpp
- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/compiler/CodeGenerator.hpp
- src/jllvm/gc/GarbageCollector.hpp
- src/jllvm/object/ClassObject.hpp
- src/jllvm/object/Object.hpp
- src/jllvm/vm/Interpreter.cpp
- src/jllvm/vm/native/Lang.cpp
This PR implements the rest of the array operations for the interpreter.
It also refactors the the relevant part of `CodeGenerator` and allocate for `AbstractArray` in `GarbageCollector`.
> [interpreter] Implement `newarray` and `multianewarray` operations

- src/jllvm/vm/Interpreter.cpp
- tests/Execution/interpreter-ineg-ub.j
The implementations of `ineg` and `lneg` incorrectly used the signed type when performing the negation. In C++ signed overflow is undefined behavior which is luckily caught by UB sanitizer.
This PR fixes that issue by simply using the unsigned type to perform the negation. Negation on unsigned is specified to behave the same as signed but without the undefined behavior.
> [interpreter] Fix UB in `*neg` implementations

- src/jllvm/vm/Interpreter.cpp
These are noops for now besides the null pointer and operand stack manipulation, just like in the JIT.
> [interpreter] Implement `monitor(enter|exit)`

- .github/workflows/builds.yml
- CMakeLists.txt
The combination of exception handling, optimizations creating empty functions and using LLD exposes an upstream issue in the toolchain which leads to `libgcc` and `libunwind` crashing on malformed data: https://github.com/llvm/llvm-project/issues/61434
This has also lead to our CI crashing: https://github.com/JLLVM/JLLVM/actions/runs/7346263904/job/20000726099
The issue is most easily worked around by not using LLD in release builds. Other fixes such as reducing our use of `llvm_unreachable` or checking whether there are compiler options to avoid emitting zero-sized functions can be considered in the future.
Until this issue is fixed upstream, change our CI to not use LLD in fully optimized builds and add code to cmake to warn when using release builds with LLD to avoid the issue.
> [ci][cmake] Workaround "bug" in LLD

- src/jllvm/materialization/LambdaMaterialization.hpp
- src/jllvm/vm/JIT.hpp
If a lambda does not have any captures it can be converted to a function pointer that can be called directly instead.
This is useful as it avoids compiling any stubs with LLVM which could otherwise not be optimized away at runtime.
> [materialization] Optimize lambda materialization for trivial lambdas

- src/jllvm/vm/Interpreter.cpp
- src/jllvm/vm/Interpreter.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
These two are very similar instructions, only differing slightly in case of `null` and the result they produce.
> [interpreter] implement `checkcast` and `instanceof`

- src/jllvm/vm/Interpreter.cpp
- src/jllvm/vm/Interpreter.hpp
- src/jllvm/vm/JIT.cpp
This PR implements all instructions that push constants onto the operand stack. LDC variants only implement the info structs that the JIT implements as well.
Note that `fmod` was added in the JIT symbols due to LLVM generating a call to it when compiling an OSR version triggered by this patch.
Depends on https://github.com/JLLVM/JLLVM/pull/275 and https://github.com/JLLVM/JLLVM/pull/286
> [interpreter] Implement constant instructions

- src/jllvm/class/ByteCodeIterator.hpp
- src/jllvm/vm/Interpreter.cpp
This PR implements the `wide` instruction for the interpreter.
It also refactors the implementation of the constant instructions. 
Depends on: #278
> [interpreter] Implement `wide` instruction

- src/jllvm/vm/Interpreter.cpp
- src/jllvm/vm/Interpreter.hpp
- tests/Execution/interpreter-checkcast-crash.j
The optimization is sadly somewhat problematic in `checkcast` specifically as it makes it impossible/hard to create a proper error message for the exception in this case.
Furthermore, the spec arguably requires loading of the class and throwing any class loading related exceptions if it were to fail. This PR therefore undoes the optimization for the time being.
> [interpreter] Undo loaded class optimization in `checkcast` and `instanceof`

- src/jllvm/class/ByteCodeIterator.hpp
- src/jllvm/vm/Interpreter.cpp
Most of these are relatively straightforward with the only oddity being the shift operations. These require masking to avoid undefined behavior in C++ and always use `int` as RHS.
> [interpreter] Implement bitwise operations

- src/jllvm/class/ByteCodeIterator.hpp
- src/jllvm/vm/Interpreter.cpp
Most of the instructions could luckily be implemented using C++s conversion operators with the exception of floating point to integer casts where undefined behaviour in C++ had to be avoided using manual checks.
> [interpreter] implement conversion instructions

- src/jllvm/class/ByteCodeIterator.hpp
- src/jllvm/vm/Interpreter.cpp
These are the last arithmetic instructions left unimplemented in the interpreter. While `lcmp` is straight forward, `fcmp` and `dcmp` have two variants which differ in behavior when an operand is a NaN.
> [interpreter] Implement `dcmp`, `fcmp` and `lcmp`

- src/jllvm/vm/Interpreter.cpp
- tests/Execution/land-lor-lxor-lcmp.java
The spec explicitly requires using signed comparison. This slipped through due to OSR being performed in the test when a `print` call is performed but becomes an issue once rebased on the PR implementing `invoke*` ops.
> [interpreter] Fix bug in `lcmp` implementation using unsigned comparison

- src/jllvm/class/ByteCode.def
- src/jllvm/class/ByteCodeIterator.cpp
- src/jllvm/class/ByteCodeIterator.hpp
- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/compiler/CodeGeneratorUtils.cpp
- src/jllvm/support/BigEndianArrayRef.hpp
- src/jllvm/vm/Interpreter.cpp
`LookupSwitch` and `TableSwitch` were the only two non-trivial types in the bytecode leading to the variant as a whole to be non-trivial. Furthermore, representing TableSwitch as a LookupSwitch made the former `O(log n)` in the interpreter rather than `O(1)` now.
This PR fixes these issues by getting rid of the `std::vector` used in both instructions and replacing it with a `BigEndianArrayRef` implemented as part of this PR that refers to the storage in the `Code` object for the tables.
While I failed to measure any performance benefit in startup, the executable size of a release build with debug info did reduce by 2 MB. I suspect this is partly due to the removal of a few exception handlers in the interpreter loop
> [class] Optimize `*switch` instruction representations

- src/jllvm/vm/NativeImplementation.cpp
- src/jllvm/vm/native/IO.hpp
- tests/Execution/file-input-stream-clinit.java
This is required by the startup sequence of `System` as it calls `new` on `FileInputStream`.
This has so far not been an issue due to a bug in the JIT compiler where `new` does not trigger class object initialization. The interpreter does implement this correctly and therefore requires class initialization of `FileInputStream` to succeed.
> [native] Implement `clinit` of `FileInputStream`

- src/jllvm/support/BitArrayRef.hpp
- unittests/BitArrayRefTests.cpp
The code triggers UB in the case that the index used is 32 or larger. The reason is the use of the `1` constant which defaults to `int` in C++. Shifting that constant by more than 31 bits is UB and triggered an assertion when built with UBSAN.
This PR fixes that by creating a nicely named constant which is the value 1 cast to the integer type.
> [support] Fix UB in BitArrayRef

- src/jllvm/vm/native/Lang.hpp
- tests/System/thread.java
This PR adds all native methods for `Thread` leaving some as TODOs.
The implementation of the rest imitate thread lifecycle of a multi-threaded system on the current single-threaded vm.
Fixes: #296
> [native] Add all and implement most native methods for `Thread`

- src/jllvm/compiler/ByteCodeCompileUtils.cpp
- src/jllvm/compiler/ByteCodeCompileUtils.hpp
- src/jllvm/compiler/ClassObjectStubCodeGenerator.cpp
- src/jllvm/compiler/CodeGenerator.cpp
- tests/Execution/new-clinit.java
This PR fixes a bug, where the `new` instruction did not initialize its class object leading to a conformance issue.
Fixes: #297
> [compiler] Fix class initialization for `new` in JIT

- src/jllvm/materialization/CMakeLists.txt
- src/jllvm/materialization/Interpreter2JITAdaptorDefinitionsGenerator.cpp
- src/jllvm/materialization/Interpreter2JITAdaptorDefinitionsGenerator.hpp
- src/jllvm/materialization/Interpreter2JITLayer.cpp
- src/jllvm/materialization/Interpreter2JITLayer.hpp
- src/jllvm/object/ClassObject.cpp
- src/jllvm/object/ClassObject.hpp
- src/jllvm/vm/Executor.hpp
- src/jllvm/vm/Interpreter.cpp
- src/jllvm/vm/Interpreter.hpp
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/JIT.hpp
- src/jllvm/vm/JNIBridge.cpp
- src/jllvm/vm/JNIBridge.hpp
- src/jllvm/vm/Runtime.cpp
- src/jllvm/vm/Runtime.hpp
This PR largely builds on the runtime refactor to introduce a new interface to all executors, allowing all methods to be called with the so-called interpreter calling convention as well.
The interpreter calling convention allows easily calling the resolved method using a reference to the operand stack. A special adaptor layer has been implemented to translate from the interpreter calling convention to the JIT calling convention, allowing the interpreter to call methods implemented in the JIT as well.
Note that this PR is only the minimal working version and is not very optimized. In particular, the interpreter does not cache any method resolutions or selections, nor does it yet directly implement the interpreter calling convention yet, instead relying on the adaptor.
These are seen as …
> [interpreter] Implement invoke* instructions

- src/jllvm/vm/native/Lang.hpp
- tests/System/thread.java
The reference OpenJDK source has `isAlive` as a native method that has to be implemented in native code: https://github.com/openjdk/jdk/blob/dfacda488bfbe2e11e8d607a6d08527710286982/src/java.base/share/classes/java/lang/Thread.java#L1053
Some distributions of the OpenJDK (e.g. Oracle, Amazon corretto) seem to ship their JDK 17s with the preview for virtual threads (https://github.com/openjdk/jdk/commit/9583e3657e43cc1c6f2101a64534564db2a9bd84) which changed the implementation to be completely in Java.
This PR implements `isAlive` to also support OpenJDKs that do not ship the preview (e.g. the builds one gets on Ubuntu or Fedora from their package managers). In the case that `isAlive` is not a `native` method, the implementation is simply ignored making this PR a noop on such …
> [native] Implement `isAlive` for some JDK 17 distros

- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/vm/Interpreter.cpp
- src/jllvm/vm/Interpreter.hpp
- src/jllvm/vm/native/Lang.hpp
This PR implements the last remaining (although mainly unused) subroutine instructions for the interpreter.
It also refactors the the lambdas in the match, in order to be in alphabetical order.
> [interpreter] Implement subroutine operations

- CMakeLists.txt
- src/jllvm/main/CMakeLists.txt
- src/jllvm/main/Main.cpp
- src/jllvm/vm/CMakeLists.txt
- src/jllvm/vm/JNIImplementation.cpp
- src/jllvm/vm/NativeImplementation.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
- unittests/CMakeLists.txt
- unittests/Inputs/TestSimpleJNI.java
- unittests/JNITests.cpp
This PR creates the most basic test infrastructure for implementing the Java Native Interface. It basically consists of a fixture containing a `VirtualMachine` instance and a `JNIEnv` that tests interact with. For this purpose, `VirtualMachine` was made easily bootable from just a single static `create` method.
Furthermore, a cmake macro was created for compiling Java files to class files. These will be able to serve as interesting inputs for the JNI interfaces (e.g. for accessing fields).
> [JNI] Create basic unit testing for JNI

- src/jllvm/class/ClassFile.hpp
- src/jllvm/object/ClassLoader.cpp
- src/jllvm/object/ClassLoader.hpp
- src/jllvm/object/ClassObject.cpp
- src/jllvm/object/ClassObject.hpp
- src/jllvm/vm/NativeImplementation.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/native/Lang.hpp
- tests/System/class.java
- unittests/GarbageCollectorTests.cpp
This PR implements the native methods `isInstance`, `isAssignableFrom`, `getSuperclass` and `getInterfaces0`.
It also correct a bug in `getName` for primitive types.
> [native] Implement more native methods for `Class`

- src/jllvm/compiler/ByteCodeCompileUtils.cpp
- src/jllvm/compiler/ByteCodeCompileUtils.hpp
- src/jllvm/compiler/CodeGenerator.cpp
- src/jllvm/compiler/CodeGenerator.hpp
- src/jllvm/compiler/Compiler.cpp
- src/jllvm/compiler/Compiler.hpp
- src/jllvm/llvm/ClassObjectStubImportPass.cpp
- src/jllvm/materialization/ByteCodeOSRCompileLayer.cpp
- src/jllvm/materialization/ByteCodeOSRCompileLayer.hpp
- src/jllvm/materialization/ByteCodeOSRLayer.cpp
- src/jllvm/materialization/ByteCodeOSRLayer.hpp
- src/jllvm/materialization/Interpreter2JITAdaptorDefinitionsGenerator.cpp
- src/jllvm/materialization/Interpreter2JITLayer.cpp
- src/jllvm/materialization/InterpreterEntry.cpp
- src/jllvm/materialization/InterpreterOSRLayer.cpp
- src/jllvm/materialization/InterpreterOSRLayer.hpp
- src/jllvm/materialization/JIT2InterpreterLayer.cpp
- src/jllvm/materialization/JNIImplementationLayer.cpp
- src/jllvm/vm/Interpreter.cpp
- src/jllvm/vm/Interpreter.hpp
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/JIT.hpp
- src/jllvm/vm/JavaFrame.cpp
- src/jllvm/vm/JavaFrame.hpp
- src/jllvm/vm/OSRState.hpp
- src/jllvm/vm/Runtime.cpp
- src/jllvm/vm/Runtime.hpp
- src/jllvm/vm/StackMapRegistrationPlugin.cpp
- tools/jllvm-jvmc/main.cpp
Our VM currently uses two calling conventions: The JIT calling convention and the Interpreter calling convention. The latter is used by the interpreter to make calls to other methods.
Prior to this PR, if the interpreter called another method in the interpreter-tier an inefficiency occurred: The interpreter currently only implements the JIT calling convention and made use of adaptors to translate between the interpreter and JIT calling convention. The JIT CC interpreter entry then translated back from the JIT calling convention to the interpreter state.
This PR fixes that by creating a new entry method into the interpreter. It is implemented in LLVM IR compiled only once on startup and is callable with just a method object and an arguments array. This entry is then used for ALL methods …
> [interpreter] Optimize interpreter calls into the interpreter

- src/jllvm/vm/NativeImplementation.cpp
- src/jllvm/vm/native/Lang.hpp
- tests/System/array.java
This PR implements the `getLength`,  `newArray` and `multiNewArray` native methods in `java.lang.reflect.Array`.
> [native] Implement native methods for `reflect.Array`

- src/jllvm/gc/RootFreeList.hpp
- src/jllvm/materialization/Interpreter2JITAdaptorDefinitionsGenerator.cpp
- src/jllvm/materialization/Interpreter2JITAdaptorDefinitionsGenerator.hpp
- src/jllvm/materialization/Interpreter2JITLayer.cpp
- src/jllvm/materialization/Interpreter2JITLayer.hpp
- src/jllvm/object/ClassObject.hpp
- src/jllvm/object/InteropHelpers.hpp
- src/jllvm/object/Object.hpp
- src/jllvm/vm/Interpreter.cpp
- src/jllvm/vm/JIT.cpp
- src/jllvm/vm/JNIBridge.cpp
- src/jllvm/vm/Runtime.cpp
- src/jllvm/vm/Runtime.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
Calling a method prior to this PR required mangling the method object followed by a lookup in the execution session. Calling the method multiple times often leads to redundantly performing the lookup multiple times.
This PR fixes that issue by now storing function pointers to both the JIT CC implementation and the interpreter CC implementations within the `Method` object. The lookups are performed once during class object preparation and reused after.
The largest performance benefits of doing this are 1) from the interpreter not requiring any lookups in the `invoke*` instructions and most importantly 2) the `Interpreter2JITLayer` implementation being heavily simplified. It no longer needs to compile a lambda materialization once per method. Instead, only the adaptor needs to be compiled …
> [object] Store implementation function pointers within `Method`

- .github/workflows/builds.yml
No clue as to when and why the rules in powershell changed for this code to stop working, but this PR fixes the recent CI failure due to incorrect parameter passing.
> [CI] Fix parameter passing in powershell

- src/jllvm/main/Main.cpp
- src/jllvm/main/Opts.td
- src/jllvm/vm/Interpreter.cpp
- src/jllvm/vm/Interpreter.hpp
- src/jllvm/vm/VirtualMachine.cpp
- src/jllvm/vm/VirtualMachine.hpp
- tests/Main/backedge-threshold.java
This PR implements the interpreter performing OSR into the JIT from within hot loops. Recognizing actual loops is not worth the effort so a simplification is made: The interpreter counts how many times a branch with a negative offset (a back edge) is taken and if taken often enough escapes into the JIT. One single back edge counter is used per method invocation. The threshold at which OSR is performed is configurable via a command line parameter.
Note that the current default value is straight up stolen from OpenJDK. I did not yet perform any "best-value" analysis and no such value exists that is perfect for every program
> [interpreter] Implement OSR in hot loops

- src/jllvm/vm/JNIImplementation.cpp
- src/jllvm/vm/JNIImplementation.hpp
- unittests/Inputs/TestSimpleJNI.java
- unittests/JNITests.cpp
This PR implements the basic happy path of the JNI methods used to access static fields. These consist of `GetStaticFieldID` to fetch a static field and then the various `GetStatic*Field` and `SetStatic*Field` methods used to read or write to static fields.
The most important part of this PR is the infrastructure setup to conveniently implement these functions. Since we need to perform type conversions from JNI to JLLVM types, metaprogramming facilities were implemented that automatically convert between lambdas using JLLVM types to the corresponding JNI types.
The current implementation does not fully implement these methods in the error case as throwing and catching exceptions is not yet implemented for the JNI.
> [JNI] Implement static field access
