JLLVM/JLLVM

.github/actions/dependencies/action.yml
.github/actions/llvm-build/action.yml
.github/workflows/builds.yml
.github/workflows/lint.yml
CMakeLists.txt
src/jllvm/materialization/ByteCodeCompileLayer.cpp
src/jllvm/materialization/JNIImplementationLayer.cpp
src/jllvm/materialization/LambdaMaterialization.hpp
src/jllvm/vm/GarbageCollector.cpp
src/jllvm/vm/JIT.cpp
src/jllvm/vm/JIT.hpp
tests/Execution/bipush.java
tools/main.cpp

This PR includes support for creating appropriate LLVM instructions on processing the bipush JVM instruction. 
Fixes https://github.com/JLLVM/JLLVM/issues/14

[instruction] Add support for bipush instruction

---

src/jllvm/materialization/ByteCodeCompileLayer.cpp
tests/Execution/iadd.java

This PR includes support for creating appropriate LLVM instructions on processing the iadd JVM instruction.
Fixes https://github.com/JLLVM/JLLVM/issues/20

[instruction] Add support for iadd instruction

---

src/jllvm/object/ClassLoader.cpp

Creating the class object for an array type has no visible side effects unlike creating class objects of normal class objects (which can cause exceptions and static initializers to run etc). It is therefore a useful optimization to create array objects eagerly if possible. This is the case when the component type of the array has already been loaded.
Creating class objects eagerly leads to better code generation in the JVM Bytecode to LLVM IR compilation and less stubs and trampolines being created.

[classloader] Eagerly create array types if possible

---

src/jllvm/materialization/ByteCodeCompileLayer.cpp
tests/Execution/imul.java

This PR includes support for creating appropriate LLVM instructions on processing the imul JVM instruction.
Fixes https://github.com/JLLVM/JLLVM/issues/29

[instruction] Add support for imul instruction

---

src/jllvm/materialization/ByteCodeCompileLayer.cpp
tests/Execution/isub.java

This PR includes support for creating appropriate LLVM instructions on processing the isub JVM instruction.
Fixes https://github.com/JLLVM/JLLVM/issues/27

[instruction] Add support for isub instruction

---

src/jllvm/materialization/ByteCodeCompileLayer.cpp
tests/Execution/basic-blocks.java

This PR improves the detection of basic blocks by linearly running through all instructions and creating new basic blocks according to branches. 
fixes https://github.com/JLLVM/JLLVM/issues/34

[codegen] Improve detection of basic blocks

---

src/jllvm/materialization/ByteCodeCompileLayer.cpp
tests/Execution/irem.java

This PR includes support for creating appropriate LLVM instructions on processing the irem JVM instruction.
fixes https://github.com/JLLVM/JLLVM/issues/49

[instruction] Implement irem instruction

---

src/jllvm/materialization/ByteCodeCompileLayer.cpp
tests/Execution/integer-comparisons.java

This PR includes support for creating appropriate LLVM instructions on processing the if_icmpeq, if_icmpne, if_icmplt, if_icmpgt, if_icmple, ifeq, ifne, iflt, ifge, ifle instructions.
fixes https://github.com/JLLVM/JLLVM/issues/53

[instruction] Implement int comparisons

---

src/jllvm/materialization/ByteCodeCompileLayer.cpp

Arrange the opcodes  in alphabetical order in the central switch statement and add TODO for not yet implemented opcodes in their respective location.

[style] Reorder opcodes in `codeGenBody`

---

src/jllvm/materialization/ByteCodeCompileLayer.cpp
tests/Execution/iaload-iastore.java

This PR includes support for creating appropriate LLVM instructions on processing the newarray, iaload and iastore instructions.
fixes https://github.com/JLLVM/JLLVM/issues/77

[instruction] Implement newarray, iaload and iastore instructions

---

src/jllvm/materialization/ByteCodeCompileLayer.cpp

LLVM by default does not a lot of structural non-local verifications, even in debug builds of LLVM. It instead requires an explicit call to a verify function which then outputs proper error messages.
Not having the verifier turned on has actually lead to silent bugs in our codegen which have luckily not really manifested themselves up until now but would lead to broken preconditions in the optimizer (I have another patch coming up where it does result in a crash). The issue was simply that `sext` and `zext` attributes were accidentally being applied to the wrong parameters in non-static methods due to not taking the `this` parameter into account. This patch fixes that.

[codegen] add LLVM module verification in debug builds and fix discovered issues

---

src/jllvm/materialization/ByteCodeCompileLayer.cpp
tests/Execution/ifnull-ifnonnull.java

These are very simply branch instructions used to check whether a reference is null or not. Easy to implement with our existing infrastructure

[instruction] Implement `ifnull` and `ifnonnull`

---

src/jllvm/materialization/CodeGenerator.cpp
tests/Execution/land-lor-lxor-lcmp.java

This PR includes support for creating appropriate LLVM instructions on processing the land, lor, lxor and lcmp JVM instructions. 
fixes https://github.com/JLLVM/JLLVM/issues/139

[instruction] Implement land, lor, lxor and lcmp instructions

---

src/jllvm/materialization/CodeGeneratorUtils.cpp
src/jllvm/object/ClassLoader.cpp
src/jllvm/object/ClassObject.cpp
src/jllvm/object/ClassObject.hpp
src/jllvm/vm/VirtualMachine.cpp

Revert "[object][NFC] Refactor assignment of V-Table and I-Table slots a bit"

---

src/jllvm/materialization/CodeGeneratorUtils.cpp
src/jllvm/object/ClassLoader.cpp
src/jllvm/object/ClassObject.cpp
src/jllvm/object/ClassObject.hpp
src/jllvm/vm/VirtualMachine.cpp

Reland "[object][NFC] Refactor assignment of V-Table and I-Table slots a bit"

---

src/jllvm/materialization/CodeGenerator.cpp

Since we know the implementations of these functions, we can tell LLVM some of their attributes in hopes of it generating better code. 
The most important of the attributes added is `gc-leaf-function`. It tells LLVM that the function can not cause garbage collection and that LLVM does not have to generate code that makes the stack parseable at that function call. 
`nocapture` tells LLVM that the pointer passed does not escape in any shape or form, which is mostly an aid for alias analysis. 
Similarily, `memory`, here with "readOnly" and "inaccessibleOrArgMemOnly" gives ensurance to LLVM that the function calls does not modify any memory in its current scope. 
`willreturn` and `nounwind` are very minor attributes that can enable some code motion.

[codegen][NFC] add optimization attributes to builtins

---

src/jllvm/vm/NativeImplementation.cpp
src/jllvm/vm/native/IO.hpp
tests/System/HelloWorld.java

This is the last commit in our Series, making the usual Java "Hello World!" run successfully :)
Depends on https://github.com/JLLVM/JLLVM/pull/178

[native] Implement 'FileOutputStream.writeBytes'

---

src/jllvm/materialization/LambdaMaterialization.hpp

The current lambda materialization codegen always prepends the lamda object to the arguments, making it the first argument passed to the trampoline. This is problematic as this requires all caller arguments to be moved to new argument registers or stack slots.
This PR improves the codegen by appending the lambda object to the arguments instead, making the lambda trampoline assembly be a simple move into a register or stack slot.
Example assembly before:
This is a lambda with 6 arguments (excluding `this`) being used in our JNI interface.
New assembly after this PR:

[materialization] Improve codegen of lambda materialization

---

src/jllvm/vm/VirtualMachine.cpp
tests/Execution/args.java

This PR implements the passing of command line arguments to the main java method.
Fixes: #81

[vm] Pass args to main

---

src/jllvm/object/ClassLoader.cpp
src/jllvm/vm/JIT.cpp
src/jllvm/vm/VirtualMachine.cpp
src/jllvm/vm/VirtualMachine.hpp
src/jllvm/vm/native/JDK.hpp
src/jllvm/vm/native/Lang.cpp
src/jllvm/vm/native/Lang.hpp
tests/Execution/athow-null.java
tests/Execution/unsafe-compare-and-set.java
tests/System/arraycopy.java

This PR implements correctly throwing all required exceptions for all native methods implemented so far.
It also adds an execution test forgotten earlier.

[native] Implement throwing exceptions in native methods

---

src/jllvm/class/ByteCodeIterator.hpp
src/jllvm/vm/Interpreter.cpp

This PR implements all operations capable of changing the instruction pointer. These are the various `if` instructions, `goto` for unconditional branches and the two switch instructions.

[interpreter] Implement branch operations

---

src/jllvm/vm/NativeImplementation.hpp

The previous implementation needlessly passed function pointers and pointer to methods around despite them being constant arguments. The created lambdas captured these making it pretty much impossible for the compiler to inline and resolve the callee at compile time. This PR simply replaces the argument with an instantiation of `std::integral_constant` allowing deduction of `ptr` as a non-type template argument.
The further inlining especially helps implementations of shorter methods where the call overhead previously dominated.

[native] Optimize `createMethodBridge`

---

src/jllvm/vm/NativeImplementation.cpp
src/jllvm/vm/native/Lang.hpp
tests/Execution/class-forname.java

This method is a basic reflection mechanism that allows loading a class object via name. It additionally makes it possible to trigger class initialization of a class object.

[native] Implement `Class.forName0`
